#!/usr/bin/env python3
"""Render the tb_int report tree from the current planning docs.

This local generator is intentionally conservative:
- it preserves existing evidence-backed pages under REPORT/
- it backfills missing per-case / per-cross / per-random-growth pages
- it emits explicit implemented-but-not-yet-evidenced stubs instead of fabricating execution data

The source of truth for scenario text remains the planning markdown:
  DV_BASIC.md, DV_EDGE.md, DV_PROF.md, DV_ERROR.md, DV_CROSS.md
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import OrderedDict
from pathlib import Path


GEN_MARK = "<!-- generated by tb_int/scripts/dv_report_gen.py: implemented stub -->"
LEGACY_GEN_MARKS = (
    "<!-- generated by tb_int/scripts/dv_report_gen.py: placeholder -->",
)

CASE_DOCS = OrderedDict(
    [
        ("BASIC", "DV_BASIC.md"),
        ("EDGE", "DV_EDGE.md"),
        ("PROF", "DV_PROF.md"),
        ("ERROR", "DV_ERROR.md"),
    ]
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tb", default="tb_int", help="path to the tb_int root")
    return parser.parse_args()


def split_md_row(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().split("|")[1:-1]]


def stage_pretty(stage: str) -> str:
    if not stage:
        return "pending"
    if "·" in stage:
        return stage
    if "/" in stage:
        return " · ".join(part.strip() for part in stage.split("/") if part.strip())
    return stage


def bucket_short(bucket: str) -> str:
    return {
        "BASIC": "B",
        "EDGE": "E",
        "PROF": "P",
        "ERROR": "X",
    }[bucket]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not content.endswith("\n"):
        content += "\n"
    path.write_text(content, encoding="utf-8")


def is_generated_stub(text: str) -> bool:
    if GEN_MARK in text:
        return True
    return any(mark in text for mark in LEGACY_GEN_MARKS)


def keep_existing(path: Path) -> bool:
    if not path.exists():
        return False
    text = read_text(path)
    return not is_generated_stub(text)


def parse_case_catalog(doc_path: Path, bucket: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    prefix = bucket_short(bucket)
    pattern = re.compile(rf"^\|\s*({prefix}\d{{3}})\s*\|")

    for raw_line in read_text(doc_path).splitlines():
        if not pattern.match(raw_line):
            continue
        cols = split_md_row(raw_line)
        if len(cols) < 6:
            continue
        rows.append(
            {
                "case_id": cols[0],
                "bucket": bucket,
                "method": cols[1],
                "implementation": cols[2],
                "scenario": cols[3],
                "primary_checks": cols[4],
                "stage": cols[5],
            }
        )
    return rows


def parse_cross_catalog(doc_path: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    pattern = re.compile(r"^\|\s*(CROSS-\d{3})\s*\|")

    for raw_line in read_text(doc_path).splitlines():
        if not pattern.match(raw_line):
            continue
        cols = split_md_row(raw_line)
        if len(cols) < 4:
            continue
        rows.append(
            {
                "run_id": cols[0],
                "mode": cols[1].strip("`"),
                "scope": cols[2],
                "notes": cols[3],
            }
        )
    return rows


def case_placeholder(row: dict[str, str]) -> str:
    case_id = row["case_id"]
    bucket = row["bucket"]
    method = row["method"]
    implementation = row["implementation"]
    scenario = row["scenario"]
    primary_checks = row["primary_checks"]
    stage = stage_pretty(row["stage"])
    bucket_doc = f"../../DV_{bucket}.md"
    bucket_page = f"../buckets/{bucket}.md"
    seed = "pending" if method.upper() == "R" else "n/a"

    return f"""# `{case_id}.md` — per-case evidence

{GEN_MARK}

- **case_id:** `{case_id}`
- **bucket:** `{bucket}`
- **scenario:** {scenario}
- **contract anchor:** implemented in the listed harness family. See the planning row in [`{bucket_doc}`]({bucket_doc}) for the scenario contract and expected checks.
- **stage taps:** `{stage}`
- **status:** `⚠️ implemented, isolated evidence pending`

## Execution method

| method | harness | make_target | plusargs | seed |
|:---:|---|---|---|---|
| {method} | `{implementation}` | implemented via catalog-declared harness | pending promotion | `{seed}` |

## Execution evidence

| outcome | sim_time | txn_count | ingress_hits | opq_hits | dma_hits | payload_words | padding_words | ghost_missing | log_path | ucdb_path |
|:---:|---|---:|---:|---:|---:|---:|---:|---|---|---|
| ⚠️ implemented | pending | pending | pending | pending | pending | pending | pending | pending | pending | pending |

## Implemented checks

- **primary checks:** {primary_checks}
- **generator note:** implemented case stub emitted so the report tree remains structurally complete while isolated UCDB/log evidence is still pending for this case.

## Isolated coverage

| metric | value | target | note |
|---|---:|---:|---|
| stmt | pending | 95.0 | isolated UCDB not yet promoted |
| branch | pending | 90.0 | isolated UCDB not yet promoted |
| cond | pending | 85.0 | isolated UCDB not yet promoted |
| expr | pending | 85.0 | isolated UCDB not yet promoted |
| fsm_state | pending | 95.0 | isolated UCDB not yet promoted |
| fsm_trans | pending | 90.0 | isolated UCDB not yet promoted |
| toggle | pending | 80.0 | isolated UCDB not yet promoted |
| functional | pending | bucket-dependent | linked via [`../../DV_CROSS.md`](../../DV_CROSS.md) |

## Linked evidence

- Planning row: [`{bucket_doc}`]({bucket_doc})
- Bucket ordered-merge trace: [`{bucket_page}`]({bucket_page})
- Continuous-frame baselines: [`../cross/README.md`](../cross/README.md)
- Bug ledger: [`../../BUG_HISTORY.md`](../../BUG_HISTORY.md)
"""


def cross_placeholder(row: dict[str, str]) -> str:
    run_id = row["run_id"]
    mode = row["mode"]
    scope = row["scope"]
    notes = row["notes"]
    return f"""# `{run_id}.md` — continuous-frame signoff run

{GEN_MARK}

- **run_id:** `{run_id}`
- **mode:** `{mode}`
- **scope:** {scope}
- **status:** `⚠️ planned run shape captured, promoted evidence pending`

## Planned run contract

| field | value |
|---|---|
| mode | `{mode}` |
| scope | {scope} |
| promoted invocation | pending |
| seed / replay source | pending |
| notes | {notes} |

## Coverage and counter checks

| field | value |
|---|---|
| code coverage | pending |
| functional cross pct | pending |
| ingress/opq/dma hit check | pending |
| payload / padding words | pending |
| dma_done / end-of-event | pending |
| ucdb path | pending |
| waveform / log | pending |

## Notes

- This page is a generated implemented stub. The run id is declared in [`../../DV_CROSS.md`](../../DV_CROSS.md) and indexed from [`README.md`](README.md).
- Replace pending fields with promoted evidence through the generator input, not by hand.
"""


def txn_growth_placeholder(row: dict[str, str]) -> str:
    case_id = row["case_id"]
    scenario = row["scenario"]
    return f"""# `REPORT/txn_growth/{case_id}.md` — checkpoint coverage curve

{GEN_MARK}

- **case_id:** `{case_id}`
- **scenario:** {scenario}
- **status:** `⚠️ random-case checkpoint stub, promoted UCDB checkpoints pending`

## Growth curve

| txn | stmt | branch | cond | expr | fsm_state | fsm_trans | toggle | ucdb_path |
|---:|---:|---:|---:|---:|---:|---:|---:|---|
| 1 | pending | pending | pending | pending | pending | pending | pending | pending |
| 2 | pending | pending | pending | pending | pending | pending | pending | pending |
| 4 | pending | pending | pending | pending | pending | pending | pending | pending |
| 8 | pending | pending | pending | pending | pending | pending | pending | pending |
| 16 | pending | pending | pending | pending | pending | pending | pending | pending |
| 32 | pending | pending | pending | pending | pending | pending | pending | pending |
| 64 | pending | pending | pending | pending | pending | pending | pending | pending |
| 128 | pending | pending | pending | pending | pending | pending | pending | pending |

## Notes

- Implemented stub emitted because the checkpoint UCDB hook is not yet promoted for this random/soak case.
- See [`README.md`](README.md) and [`../../DV_PROF.md`](../../DV_PROF.md) for the planned cadence and intended saturation analysis.
"""


def main() -> int:
    args = parse_args()
    tb = Path(args.tb).resolve()
    if not tb.is_dir():
        print(f"error: tb directory not found: {tb}", file=sys.stderr)
        return 2

    report = tb / "REPORT"
    (report / "cases").mkdir(parents=True, exist_ok=True)
    (report / "cross").mkdir(parents=True, exist_ok=True)
    (report / "txn_growth").mkdir(parents=True, exist_ok=True)

    case_rows: list[dict[str, str]] = []
    for bucket, filename in CASE_DOCS.items():
        case_rows.extend(parse_case_catalog(tb / filename, bucket))

    cross_rows = parse_cross_catalog(tb / "DV_CROSS.md")

    created_cases = 0
    preserved_cases = 0
    for row in case_rows:
        path = report / "cases" / f"{row['case_id']}.md"
        if keep_existing(path):
            preserved_cases += 1
            continue
        write_text(path, case_placeholder(row))
        created_cases += 1

    created_cross = 0
    preserved_cross = 0
    for row in cross_rows:
        path = report / "cross" / f"{row['run_id']}.md"
        if keep_existing(path):
            preserved_cross += 1
            continue
        write_text(path, cross_placeholder(row))
        created_cross += 1

    created_growth = 0
    preserved_growth = 0
    for row in case_rows:
        if row["bucket"] != "PROF":
            continue
        path = report / "txn_growth" / f"{row['case_id']}.md"
        if keep_existing(path):
            preserved_growth += 1
            continue
        write_text(path, txn_growth_placeholder(row))
        created_growth += 1

    print(
        "generated report stubs: "
        f"cases created={created_cases} preserved={preserved_cases}; "
        f"cross created={created_cross} preserved={preserved_cross}; "
        f"txn_growth created={created_growth} preserved={preserved_growth}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
