import time

odb_path_base = "/Equipment/Quads Config"

odb_path_commands = odb_path_base + "/Settings/Readout"
odb_path_config = odb_path_base + "/Settings/Config"
odb_path_variables = odb_path_base + "/Variables"
odb_path_links = odb_path_base + "/Settings/DAQ/Links"
odb_path_vdacs = odb_path_config + "/VDACS"
odb_path_modes = odb_path_config + "/MODES"
odb_path_daq_commands = odb_path_base + "/Settings/DAQ/Commands"

odb_path_minalyzer = "/PixelOperation/TuningSettings"
odb_path_minalyzer_output = "/PixelOperation/TuningOutput"


#### Mapping

def get_chip_list(seq):
    """Retrieve the list of chips from the ODB"""
    asic_mask = seq.odb_get(odb_path_links + "/ASICMask")
    N_CHIPS = 8
    N_FEBS = 4
    chip_list = []
    for feb in range(N_FEBS):
        n_asics = int(asic_mask[feb]).bit_length()
        for i in range(n_asics):
            if (asic_mask[feb] >> i) & 1:
                chip_list.append(feb * N_CHIPS + i)
            
    return chip_list

#### Chip Handling

def set_chip_dac(seq, chip, dac, value):
    seq.odb_set(f"{odb_path_vdacs}/{dac}[{chip}]", value)

def set_chips_dac(seq, chips, dac, value):
    """Set a DAC value for a list of chips"""
    for chip in chips:
        set_chip_dac(seq, chip, dac, value)

def set_chip_mode(seq, chip, mode, value):
    seq.odb_set(f"{odb_path_modes}/{mode}[{chip}]", value)

def set_chips_mode(seq, chips, mode, value):
    """Set a mode value for a list of chips"""
    for chip in chips:
        set_chip_mode(seq, chip, mode, value)
    


def configure_chips(seq):
    """Applies configuration to all chips (broadcast)"""
    seq.odb_set(odb_path_commands + "/MupixConfig", 1)
    
    # Wait for configuration to finish
    time.sleep(0.1)
    while seq.odb_get(odb_path_commands + "/MupixConfig") == 1:
        time.sleep(0.1)

def configure_tdacs(seq):
    """Applies TDAC configuration to all chips (broadcast)"""
    seq.odb_set(odb_path_commands + "/MupixTDACConfig", 1)
    
    # Wait for configuration to finish
    time.sleep(0.1)
    while seq.odb_get(odb_path_commands + "/MupixTDACConfig") == 1:
        time.sleep(0.1)

def reset_pll(seq, chips):
    """Resets PLL for the given list of chips"""
    set_chips_dac(seq, chips, "EnPLL", 1)
    configure_chips(seq)
    time.sleep(0.2)
    set_chips_dac(seq, chips, "EnPLL", 0)
    configure_chips(seq)


#### DAQ Handling

def feb_set_to_running(seq):
    seq.odb_set(odb_path_daq_commands + "/Run Cycle FEB", 1)
    while seq.odb_get(odb_path_commands + "/Run Cycle FEB") == 1:
        time.sleep(0.1)
        
#### Minalyzer

def setup_minalyzer(seq, max_hits, max_link_errors, do_tuning):
    seq.odb_set(odb_path_minalyzer + "/Algo", "MaxHits")
    seq.odb_set(odb_path_minalyzer + "/MaxHits", max_hits)
    seq.odb_set(odb_path_minalyzer + "/DoTune", do_tuning)
    seq.odb_set(odb_path_minalyzer + "/TakeData", False)
    seq.odb_set(odb_path_minalyzer + "/MasksAreGenerated", False)
    seq.odb_set(odb_path_minalyzer + "/Iteration", 0)
    seq.odb_set(odb_path_minalyzer + "/EnableMaskGeneration", True)
    seq.odb_set(odb_path_minalyzer + "/MaxLinkErrors", max_link_errors)

def run_minalyzer(seq, iteration, run_time):
    seq.odb_set(odb_path_minalyzer + "/Iteration", iteration) 
    seq.odb_set(odb_path_minalyzer + "/TakeData", True)
    seq.msg("Start taking data")
    
    time.sleep(run_time)
    
    seq.odb_set(odb_path_minalyzer + "/TakeData", False)
    seq.msg("Stop taking data")
    
    # Wait for masks to be generated by Minalyzer
    while not seq.odb_get(odb_path_minalyzer + "/MasksAreGenerated"):
        time.sleep(0.05)
    
    # Reset flag
    seq.odb_set(odb_path_minalyzer + "/MasksAreGenerated", False)
