name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdoxy mkdocs-with-pdf
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Build MkDocs
        run: mkdocs build

      - name: Configure Git
        run: |
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.local"

      - name: Push to gitea-pages branch
        run: |
          git checkout --orphan gitea-pages
          git reset --hard
          mv site/* .
          git add .
          git commit -m "Update site - $(date)"
          git push -f https://${{ secrets.GITHUB_TOKEN }}@gitea.psi.ch/${{ github.repository }}.git gitea-pages
