/* AUTO-GENERATED by generate_beamtime26_qc.py. DO NOT EDIT. */
/*
 * MuTRiG3 configuration field descriptors shared by the NIOS
 * live-configuration browser and host-side consistency tests.
 *
 * Tcl schema SHA-256: b2533b11eed71c059e9de3dd5a2f97e4b6b569276a232b09d57b23363e5f33d3
 * MIDAS schema SHA-256: 819509ffb66ab6149856d4e5d6d018c88d96da3c01c16b83e94cea39c5c4e841
 */

#ifndef MUTRIG3_CONFIG_SCHEMA_H_
#define MUTRIG3_CONFIG_SCHEMA_H_

#include <stdint.h>

namespace mutrig3_config {

enum field_order_t : uint8_t {
    FIELD_BIG_ENDIAN = 0,
    FIELD_LITTLE_ENDIAN = 1
};

struct field_descriptor_t {
    const char* name;
    uint16_t offset;
    uint8_t width;
    field_order_t order;
};

static const field_descriptor_t HEADER_FIELDS[18] = {
    {"gen_idle", 0, 1, FIELD_BIG_ENDIAN},
    {"sync_ch_rst", 1, 1, FIELD_BIG_ENDIAN},
    {"ext_trig_mode", 2, 1, FIELD_BIG_ENDIAN},
    {"ext_trig_endtime_sign", 3, 1, FIELD_BIG_ENDIAN},
    {"ext_trig_offset", 4, 4, FIELD_LITTLE_ENDIAN},
    {"ext_trig_endtime", 8, 4, FIELD_LITTLE_ENDIAN},
    {"ms_limits", 12, 5, FIELD_LITTLE_ENDIAN},
    {"ms_switch_sel", 17, 1, FIELD_BIG_ENDIAN},
    {"ms_debug", 18, 1, FIELD_BIG_ENDIAN},
    {"tx_mode", 19, 3, FIELD_LITTLE_ENDIAN},
    {"pll_setcoarse", 22, 1, FIELD_BIG_ENDIAN},
    {"pll_envomonitor", 23, 1, FIELD_BIG_ENDIAN},
    {"disable_coarse", 24, 1, FIELD_BIG_ENDIAN},
    {"pll_lol_dbg", 25, 1, FIELD_BIG_ENDIAN},
    {"en_ch_evt_cnt", 26, 1, FIELD_BIG_ENDIAN},
    {"dmon_sel", 27, 5, FIELD_BIG_ENDIAN},
    {"dmon_sel_enable", 32, 1, FIELD_BIG_ENDIAN},
    {"dmon_sw", 33, 1, FIELD_BIG_ENDIAN},
};

static const field_descriptor_t CHANNEL_FIELDS[29] = {
    {"energy_c_en", 0, 1, FIELD_BIG_ENDIAN},
    {"energy_r_en", 1, 1, FIELD_BIG_ENDIAN},
    {"sswitch", 2, 1, FIELD_BIG_ENDIAN},
    {"cm_sensing_high_r", 3, 1, FIELD_BIG_ENDIAN},
    {"amon_en_n", 4, 1, FIELD_BIG_ENDIAN},
    {"edge", 5, 1, FIELD_BIG_ENDIAN},
    {"edge_cml", 6, 1, FIELD_BIG_ENDIAN},
    {"cml_sc", 7, 1, FIELD_BIG_ENDIAN},
    {"tdctest_n", 8, 1, FIELD_BIG_ENDIAN},
    {"amonctrl", 9, 3, FIELD_BIG_ENDIAN},
    {"comp_spi", 12, 2, FIELD_BIG_ENDIAN},
    {"tthresh_offset_1", 14, 1, FIELD_BIG_ENDIAN},
    {"sipm", 15, 6, FIELD_BIG_ENDIAN},
    {"tthresh_offset_2", 21, 1, FIELD_BIG_ENDIAN},
    {"tthresh_sc", 22, 2, FIELD_BIG_ENDIAN},
    {"tthresh", 24, 6, FIELD_BIG_ENDIAN},
    {"ampcom_sc", 30, 2, FIELD_BIG_ENDIAN},
    {"ampcom", 32, 6, FIELD_BIG_ENDIAN},
    {"tthresh_offset_0", 38, 1, FIELD_BIG_ENDIAN},
    {"inputbias", 39, 6, FIELD_BIG_ENDIAN},
    {"ethresh", 45, 8, FIELD_BIG_ENDIAN},
    {"ebias", 53, 3, FIELD_BIG_ENDIAN},
    {"pole_sc", 56, 1, FIELD_BIG_ENDIAN},
    {"pole", 57, 6, FIELD_BIG_ENDIAN},
    {"cml", 63, 4, FIELD_BIG_ENDIAN},
    {"delay", 67, 1, FIELD_BIG_ENDIAN},
    {"pole_en_n", 68, 1, FIELD_BIG_ENDIAN},
    {"mask", 69, 1, FIELD_BIG_ENDIAN},
    {"recv_all", 70, 1, FIELD_BIG_ENDIAN},
};

static const field_descriptor_t TDC_FIELDS[25] = {
    {"vnd2c_scale", 2306, 1, FIELD_BIG_ENDIAN},
    {"vnd2c_offset", 2307, 2, FIELD_BIG_ENDIAN},
    {"vnd2c", 2309, 6, FIELD_BIG_ENDIAN},
    {"vncntbuffer_scale", 2315, 1, FIELD_BIG_ENDIAN},
    {"vncntbuffer_offset", 2316, 2, FIELD_BIG_ENDIAN},
    {"vncntbuffer", 2318, 6, FIELD_BIG_ENDIAN},
    {"vncnt_scale", 2324, 1, FIELD_BIG_ENDIAN},
    {"vncnt_offset", 2325, 2, FIELD_BIG_ENDIAN},
    {"vncnt", 2327, 6, FIELD_BIG_ENDIAN},
    {"vnpcp_scale", 2333, 1, FIELD_BIG_ENDIAN},
    {"vnpcp_offset", 2334, 2, FIELD_BIG_ENDIAN},
    {"vnpcp", 2336, 6, FIELD_BIG_ENDIAN},
    {"vnvcodelay_scale", 2342, 1, FIELD_BIG_ENDIAN},
    {"vnvcodelay_offset", 2343, 2, FIELD_BIG_ENDIAN},
    {"vnvcodelay", 2345, 6, FIELD_BIG_ENDIAN},
    {"vnvcobuffer_scale", 2351, 1, FIELD_BIG_ENDIAN},
    {"vnvcobuffer_offset", 2352, 2, FIELD_BIG_ENDIAN},
    {"vnvcobuffer", 2354, 6, FIELD_BIG_ENDIAN},
    {"vnhitlogic_scale", 2360, 1, FIELD_BIG_ENDIAN},
    {"vnhitlogic_offset", 2361, 2, FIELD_BIG_ENDIAN},
    {"vnhitlogic", 2363, 6, FIELD_BIG_ENDIAN},
    {"vnpfc_scale", 2369, 1, FIELD_BIG_ENDIAN},
    {"vnpfc_offset", 2370, 2, FIELD_BIG_ENDIAN},
    {"vnpfc", 2372, 6, FIELD_BIG_ENDIAN},
    {"latchbias", 2378, 12, FIELD_LITTLE_ENDIAN},
};

static const field_descriptor_t FOOTER_FIELDS[51] = {
    {"coin_xbar_lower_rx_ena", 2390, 1, FIELD_BIG_ENDIAN},
    {"coin_xbar_lower_tx_ena", 2391, 1, FIELD_BIG_ENDIAN},
    {"coin_xbar_lower_tx_vdac", 2392, 8, FIELD_BIG_ENDIAN},
    {"coin_xbar_lower_tx_idac", 2400, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_xbl", 2406, 3, FIELD_BIG_ENDIAN},
    {"coin_mat_0", 2409, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_1", 2415, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_2", 2421, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_3", 2427, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_4", 2433, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_5", 2439, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_6", 2445, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_7", 2451, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_8", 2457, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_9", 2463, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_10", 2469, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_11", 2475, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_12", 2481, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_13", 2487, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_14", 2493, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_15", 2499, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_16", 2505, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_17", 2511, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_18", 2517, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_19", 2523, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_20", 2529, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_21", 2535, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_22", 2541, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_23", 2547, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_24", 2553, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_25", 2559, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_26", 2565, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_27", 2571, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_28", 2577, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_29", 2583, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_30", 2589, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_31", 2595, 6, FIELD_BIG_ENDIAN},
    {"coin_mat_xbu", 2601, 3, FIELD_BIG_ENDIAN},
    {"coin_xbar_upper_rx_ena", 2604, 1, FIELD_BIG_ENDIAN},
    {"coin_xbar_upper_tx_ena", 2605, 1, FIELD_BIG_ENDIAN},
    {"coin_xbar_upper_tx_vdac", 2606, 8, FIELD_BIG_ENDIAN},
    {"coin_xbar_upper_tx_idac", 2614, 6, FIELD_BIG_ENDIAN},
    {"coin_wnd", 2620, 1, FIELD_BIG_ENDIAN},
    {"amon_en", 2621, 1, FIELD_BIG_ENDIAN},
    {"amon_dac", 2622, 8, FIELD_BIG_ENDIAN},
    {"dmon_1_en", 2630, 1, FIELD_BIG_ENDIAN},
    {"dmon_1_dac", 2631, 8, FIELD_BIG_ENDIAN},
    {"dmon_2_en", 2639, 1, FIELD_BIG_ENDIAN},
    {"dmon_2_dac", 2640, 8, FIELD_BIG_ENDIAN},
    {"lvds_tx_vcm", 2648, 8, FIELD_BIG_ENDIAN},
    {"lvds_tx_bias", 2656, 6, FIELD_BIG_ENDIAN},
};

enum : uint8_t {
    HEADER_FIELD_COUNT = 18,
    CHANNEL_FIELD_COUNT = 29,
    TDC_FIELD_COUNT = 25,
    FOOTER_FIELD_COUNT = 51
};

} // namespace mutrig3_config

#endif /* MUTRIG3_CONFIG_SCHEMA_H_ */
