-- -----------------------------------------------------------------------------
-- File      : tb_swb_cross_ghdl.vhd
-- Purpose   : Scheduled GHDL waveform fixture for MuSiP SWB/OPQ packet evidence.
--
-- The packet streams are read from replay/*.mem files generated by
-- scripts/gen_swb_cross_replay.py. Those files use the same basic-case
-- reference builder that feeds the UVM sequence, so this fixture is a waveform
-- display/replay harness rather than an independent OPQ timing model.
-- -----------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_textio.all;

use std.env.all;
use std.textio.all;

entity tb_swb_cross_ghdl is
generic (
    G_CASE_CYCLES     : positive := 24576;
    G_CLOCK_PERIOD_NS : positive := 4
);
end entity;

architecture sim of tb_swb_cross_ghdl is

    constant C_CLK_PERIOD : time := G_CLOCK_PERIOD_NS * 1 ns;

    subtype t_data_word is std_logic_vector(31 downto 0);
    subtype t_datak_word is std_logic_vector(3 downto 0);
    subtype t_stream_word is std_logic_vector(35 downto 0);
    subtype t_event_word is std_logic_vector(47 downto 0);
    subtype t_word_kind is unsigned(4 downto 0);
    subtype t_header_id is unsigned(5 downto 0);
    subtype t_lane_id is unsigned(1 downto 0);
    subtype t_provenance_id is unsigned(2 downto 0);
    subtype t_halfword is unsigned(15 downto 0);
    subtype t_timestamp is unsigned(47 downto 0);
    subtype t_lane_mask is std_logic_vector(3 downto 0);

    type t_nat4 is array (0 to 3) of natural;
    type t_stream_word4 is array (0 to 3) of t_stream_word;
    type t_ts_state is record
        ts_high : unsigned(31 downto 0);
        ts_low  : unsigned(15 downto 0);
    end record;

    type t_case_cfg is record
        code         : natural;
        bucket       : natural;
        lane_skew    : natural;
        dma_bp_pct   : natural;
        error_path   : boolean;
        csr_activity : boolean;
    end record;
    type t_case_array is array (natural range <>) of t_case_cfg;

    constant C_BUCKET_BASIC : natural := 0;
    constant C_BUCKET_PROF  : natural := 2;
    constant C_BUCKET_ERROR : natural := 3;
    constant C_BUCKET_CSR   : natural := 4;

    constant C_KIND_IDLE             : natural := 0;
    constant C_KIND_SOP_HEADER       : natural := 1;
    constant C_KIND_TS_HIGH          : natural := 2;
    constant C_KIND_TS_LOW_PKG       : natural := 3;
    constant C_KIND_DEBUG0           : natural := 4;
    constant C_KIND_DEBUG1           : natural := 5;
    constant C_KIND_SUBHEADER        : natural := 6;
    constant C_KIND_HIT              : natural := 7;
    constant C_KIND_EOP_TRAILER      : natural := 8;
    constant C_KIND_HEADER_ERROR     : natural := 9;
    constant C_KIND_SUBHEADER_ERROR  : natural := 10;
    constant C_KIND_HIT_ERROR        : natural := 11;
    constant C_KIND_DMA_HIT_PAYLOAD  : natural := 12;

    constant C_CSR_NONE        : natural := 0;
    constant C_CSR_UID         : natural := 1;
    constant C_CSR_META        : natural := 2;
    constant C_CSR_LANE_MASK   : natural := 3;
    constant C_CSR_CTRL        : natural := 4;
    constant C_CSR_STATUS      : natural := 5;
    constant C_CSR_CAP         : natural := 6;
    constant C_CSR_FT_WR_HDR   : natural := 7;
    constant C_CSR_FT_WR_SHD   : natural := 8;
    constant C_CSR_FT_WR_HIT   : natural := 9;
    constant C_CSR_FT_RD_HDR   : natural := 10;
    constant C_CSR_FT_RD_SHD   : natural := 11;
    constant C_CSR_FT_RD_HIT   : natural := 12;
    constant C_CSR_FT_DROP_HDR : natural := 13;
    constant C_CSR_FT_DROP_SHD : natural := 14;
    constant C_CSR_FT_DROP_HIT : natural := 15;
    constant C_CSR_LANE_WR_HDR : natural := 16;
    constant C_CSR_LANE_WR_SHD : natural := 17;
    constant C_CSR_LANE_WR_HIT : natural := 18;
    constant C_CSR_LANE_RD_HDR : natural := 19;
    constant C_CSR_LANE_RD_SHD : natural := 20;
    constant C_CSR_LANE_RD_HIT : natural := 21;
    constant C_CSR_LANE_DROP_HDR : natural := 22;
    constant C_CSR_LANE_DROP_SHD : natural := 23;
    constant C_CSR_LANE_DROP_HIT : natural := 24;
    constant C_CSR_LANE_CREDIT   : natural := 25;
    constant C_CSR_TICKET_CREDIT : natural := 26;
    constant C_CSR_DRR_ALLOWANCE : natural := 27;
    constant C_CSR_DRR_QUANTUM   : natural := 28;
    constant C_CSR_DRR_GRANT_CNT : natural := 29;
    constant C_CSR_DRR_BEAT_CNT  : natural := 30;
    constant C_CSR_DRR_DEFER_CNT : natural := 31;
    constant C_CSR_READ_STEPS    : natural := 79;

    constant C_CSR_UID_ADDR       : natural := 16#000#;
    constant C_CSR_META_ADDR      : natural := 16#004#;
    constant C_CSR_LANE_MASK_ADDR : natural := 16#008#;
    constant C_CSR_CTRL_ADDR      : natural := 16#00C#;
    constant C_CSR_STATUS_ADDR    : natural := 16#010#;
    constant C_CSR_CAP_ADDR       : natural := 16#014#;
    constant C_CSR_FT_BASE_ADDR   : natural := 16#020#;
    constant C_CSR_LANE_BASE_ADDR : natural := 16#100#;
    constant C_CSR_LANE_STRIDE    : natural := 16#040#;

    constant C_FRAME_TS_STEP_8NS  : natural := 16#800#;
    constant C_FRAME_PERIOD_CYCLES : natural := (C_FRAME_TS_STEP_8NS * 8) / G_CLOCK_PERIOD_NS;
    constant C_LANE_FIFO_MAX_CREDIT   : natural := 1022;
    constant C_TICKET_FIFO_MAX_CREDIT : natural := 255;
    constant C_LANE_FIFO_DEPTH        : natural := 2048;
    constant C_TICKET_FIFO_DEPTH      : natural := 2048;
    constant C_DRR_DEFAULT_ALLOWANCE  : natural := 256;
    constant C_DRR_QUANTUM_MAX        : natural := 1023;
    constant C_CASES : t_case_array := (
        (1,    C_BUCKET_BASIC, 0,   0, false, false), -- B001 aligned UVM replay
        (46,   C_BUCKET_BASIC, 0,   0, false, false), -- B046 runtime lane-mask replay
        (2123, C_BUCKET_PROF,  512, 50, false, false), -- P123 skew/backpressure
        (3111, C_BUCKET_ERROR, 0,   0, true,  false), -- X111 malformed/recovery sample
        (4001, C_BUCKET_CSR,   0,   0, false, true)   -- C001 CSR read monitor
    );

    signal clk               : std_logic := '0';
    signal reset_n           : std_logic := '0';
    signal run_active        : std_logic := '0';
    signal cycle_tick        : unsigned(31 downto 0) := (others => '0');
    signal case_tick         : unsigned(31 downto 0) := (others => '0');
    signal case_index        : unsigned(7 downto 0) := (others => '0');
    signal cases_done        : unsigned(7 downto 0) := (others => '0');
    signal bucket_id         : unsigned(3 downto 0) := (others => '0');
    signal case_code         : unsigned(15 downto 0) := (others => '0');
    signal flow_state        : unsigned(3 downto 0) := (others => '0');

    signal case_sop          : std_logic := '0';
    signal case_eop          : std_logic := '0';
    signal segment_reset     : std_logic := '0';
    signal bucket_transition : std_logic := '0';
    signal frame_slot        : std_logic := '0';

    signal lane_mask             : t_lane_mask := (others => '0');
    signal lane_mask_cmd_valid   : std_logic := '0';
    signal lane_mask_cmd_value   : t_lane_mask := (others => '0');
    signal lane_valid            : std_logic_vector(3 downto 0) := (others => '0');
    signal lane_ready            : std_logic_vector(3 downto 0) := (others => '1');
    signal lane_fire             : std_logic_vector(3 downto 0) := (others => '0');

    signal lane0_word        : t_stream_word := (others => '0');
    signal lane1_word        : t_stream_word := (others => '0');
    signal lane2_word        : t_stream_word := (others => '0');
    signal lane3_word        : t_stream_word := (others => '0');
    signal lane0_data        : t_data_word := (others => '0');
    signal lane1_data        : t_data_word := (others => '0');
    signal lane2_data        : t_data_word := (others => '0');
    signal lane3_data        : t_data_word := (others => '0');
    signal lane0_datak       : t_datak_word := (others => '0');
    signal lane1_datak       : t_datak_word := (others => '0');
    signal lane2_datak       : t_datak_word := (others => '0');
    signal lane3_datak       : t_datak_word := (others => '0');
    signal lane0_word_kind   : t_word_kind := (others => '0');
    signal lane1_word_kind   : t_word_kind := (others => '0');
    signal lane2_word_kind   : t_word_kind := (others => '0');
    signal lane3_word_kind   : t_word_kind := (others => '0');
    signal lane0_header_id   : t_header_id := (others => '0');
    signal lane1_header_id   : t_header_id := (others => '0');
    signal lane2_header_id   : t_header_id := (others => '0');
    signal lane3_header_id   : t_header_id := (others => '0');
    signal lane0_source_lane : t_lane_id := (others => '0');
    signal lane1_source_lane : t_lane_id := (others => '0');
    signal lane2_source_lane : t_lane_id := (others => '0');
    signal lane3_source_lane : t_lane_id := (others => '0');
    signal lane0_frame_ts    : t_timestamp := (others => '0');
    signal lane1_frame_ts    : t_timestamp := (others => '0');
    signal lane2_frame_ts    : t_timestamp := (others => '0');
    signal lane3_frame_ts    : t_timestamp := (others => '0');
    signal lane0_hit_low     : t_halfword := (others => '0');
    signal lane1_hit_low     : t_halfword := (others => '0');
    signal lane2_hit_low     : t_halfword := (others => '0');
    signal lane3_hit_low     : t_halfword := (others => '0');

    signal join_pending      : std_logic := '0';
    signal inactive_wait     : std_logic := '0';
    signal opq_body_hold     : std_logic := '0';
    signal opq_wait_cycles   : unsigned(15 downto 0) := (others => '0');
    signal reorder_depth     : unsigned(15 downto 0) := (others => '0');

    signal ingress_words     : unsigned(31 downto 0) := (others => '0');
    signal opq_words         : unsigned(31 downto 0) := (others => '0');
    signal opq_word          : t_stream_word := (others => '0');
    signal opq_data          : t_data_word := (others => '0');
    signal opq_datak         : t_datak_word := (others => '0');
    signal opq_word_kind     : t_word_kind := (others => '0');
    signal opq_header_id     : t_header_id := (others => '0');
    signal opq_source_lane   : t_lane_id := (others => '0');
    signal opq_lane_provenance : t_provenance_id := to_unsigned(5, 3);
    signal opq_frame_ts      : t_timestamp := (others => '0');
    signal opq_hit_low       : t_halfword := (others => '0');

    signal opq_ingress_accept         : std_logic_vector(3 downto 0) := (others => '0');
    signal opq_ticket_push            : std_logic_vector(3 downto 0) := (others => '0');
    signal opq_allocator_req          : std_logic_vector(3 downto 0) := (others => '0');
    signal opq_allocator_grant        : std_logic := '0';
    signal opq_allocator_grant_lane   : std_logic_vector(3 downto 0) := (others => '0');
    signal opq_allocator_ticket_valid : std_logic := '0';
    signal opq_allocator_ticket_lane  : t_lane_id := (others => '0');
    signal opq_allocator_ticket_id    : t_halfword := (others => '0');
    signal opq_mover_cmd_valid        : std_logic := '0';
    signal opq_mover_cmd_ready        : std_logic := '0';
    signal opq_mover_cmd_lane         : t_lane_id := (others => '0');
    signal opq_mover_cmd_page         : t_halfword := (others => '0');
    signal opq_mover_data_valid       : std_logic := '0';
    signal opq_drr_req_raw            : std_logic_vector(3 downto 0) := (others => '0');
    signal opq_drr_req_eligible       : std_logic_vector(3 downto 0) := (others => '0');
    signal opq_drr_grant              : std_logic_vector(3 downto 0) := (others => '0');
    signal opq_drr_lock_event         : std_logic_vector(3 downto 0) := (others => '0');
    signal opq_drr_defer_event        : std_logic_vector(3 downto 0) := (others => '0');
    signal opq_drr_selected_lane      : t_lane_id := (others => '0');
    signal opq_drr_allowance0         : unsigned(9 downto 0) := to_unsigned(C_DRR_DEFAULT_ALLOWANCE, 10);
    signal opq_drr_allowance1         : unsigned(9 downto 0) := to_unsigned(C_DRR_DEFAULT_ALLOWANCE, 10);
    signal opq_drr_allowance2         : unsigned(9 downto 0) := to_unsigned(C_DRR_DEFAULT_ALLOWANCE, 10);
    signal opq_drr_allowance3         : unsigned(9 downto 0) := to_unsigned(C_DRR_DEFAULT_ALLOWANCE, 10);
    signal opq_drr_quantum0           : unsigned(9 downto 0) := to_unsigned(C_DRR_DEFAULT_ALLOWANCE, 10);
    signal opq_drr_quantum1           : unsigned(9 downto 0) := to_unsigned(C_DRR_DEFAULT_ALLOWANCE, 10);
    signal opq_drr_quantum2           : unsigned(9 downto 0) := to_unsigned(C_DRR_DEFAULT_ALLOWANCE, 10);
    signal opq_drr_quantum3           : unsigned(9 downto 0) := to_unsigned(C_DRR_DEFAULT_ALLOWANCE, 10);
    signal opq_page_ram_we            : std_logic := '0';
    signal opq_page_ram_waddr         : t_halfword := (others => '0');
    signal opq_page_ram_wdata         : t_stream_word := (others => '0');
    signal opq_presenter_valid        : std_logic := '0';
    signal opq_presenter_ready        : std_logic := '1';
    signal opq_lane0_fifo_usedw       : unsigned(10 downto 0) := (others => '0');
    signal opq_lane1_fifo_usedw       : unsigned(10 downto 0) := (others => '0');
    signal opq_lane2_fifo_usedw       : unsigned(10 downto 0) := (others => '0');
    signal opq_lane3_fifo_usedw       : unsigned(10 downto 0) := (others => '0');
    signal opq_lane0_fifo_wr_ptr      : unsigned(10 downto 0) := (others => '0');
    signal opq_lane1_fifo_wr_ptr      : unsigned(10 downto 0) := (others => '0');
    signal opq_lane2_fifo_wr_ptr      : unsigned(10 downto 0) := (others => '0');
    signal opq_lane3_fifo_wr_ptr      : unsigned(10 downto 0) := (others => '0');
    signal opq_lane0_fifo_rd_ptr      : unsigned(10 downto 0) := (others => '0');
    signal opq_lane1_fifo_rd_ptr      : unsigned(10 downto 0) := (others => '0');
    signal opq_lane2_fifo_rd_ptr      : unsigned(10 downto 0) := (others => '0');
    signal opq_lane3_fifo_rd_ptr      : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket0_fifo_usedw     : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket1_fifo_usedw     : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket2_fifo_usedw     : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket3_fifo_usedw     : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket0_fifo_wr_ptr    : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket1_fifo_wr_ptr    : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket2_fifo_wr_ptr    : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket3_fifo_wr_ptr    : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket0_fifo_rd_ptr    : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket1_fifo_rd_ptr    : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket2_fifo_rd_ptr    : unsigned(10 downto 0) := (others => '0');
    signal opq_ticket3_fifo_rd_ptr    : unsigned(10 downto 0) := (others => '0');
    signal opq_lane0_credit           : unsigned(10 downto 0) := to_unsigned(C_LANE_FIFO_MAX_CREDIT, 11);
    signal opq_lane1_credit           : unsigned(10 downto 0) := to_unsigned(C_LANE_FIFO_MAX_CREDIT, 11);
    signal opq_lane2_credit           : unsigned(10 downto 0) := to_unsigned(C_LANE_FIFO_MAX_CREDIT, 11);
    signal opq_lane3_credit           : unsigned(10 downto 0) := to_unsigned(C_LANE_FIFO_MAX_CREDIT, 11);
    signal opq_ticket0_credit         : unsigned(10 downto 0) := to_unsigned(C_TICKET_FIFO_MAX_CREDIT, 11);
    signal opq_ticket1_credit         : unsigned(10 downto 0) := to_unsigned(C_TICKET_FIFO_MAX_CREDIT, 11);
    signal opq_ticket2_credit         : unsigned(10 downto 0) := to_unsigned(C_TICKET_FIFO_MAX_CREDIT, 11);
    signal opq_ticket3_credit         : unsigned(10 downto 0) := to_unsigned(C_TICKET_FIFO_MAX_CREDIT, 11);
    signal opq_handle_fifo_usedw      : unsigned(10 downto 0) := (others => '0');
    signal opq_page_ram_usedw         : unsigned(15 downto 0) := (others => '0');
    signal opq_page_free_count        : unsigned(15 downto 0) := to_unsigned(4096, 16);

    signal expected_words    : unsigned(31 downto 0) := (others => '0');
    signal payload_words     : unsigned(31 downto 0) := (others => '0');
    signal dma_words         : unsigned(31 downto 0) := (others => '0');
    signal dma_word          : t_stream_word := (others => '0');
    signal dma_data          : t_data_word := (others => '0');
    signal dma_datak         : t_datak_word := (others => '0');
    signal dma_word_kind     : t_word_kind := (others => '0');
    signal dma_header_id     : t_header_id := (others => '0');
    signal dma_source_lane   : t_lane_id := (others => '0');
    signal dma_frame_ts      : t_timestamp := (others => '0');
    signal dma_hit_low       : t_halfword := (others => '0');
    signal dma_half_full     : std_logic := '0';
    signal dma_wren          : std_logic := '0';
    signal dma_done          : std_logic := '0';

    signal csr_cmd_valid        : std_logic := '0';
    signal csr_cmd_write        : std_logic := '0';
    signal csr_read_valid       : std_logic := '0';
    signal csr_readdatavalid    : std_logic := '0';
    signal csr_addr             : unsigned(15 downto 0) := (others => '0');
    signal csr_reg_id           : unsigned(7 downto 0) := (others => '0');
    signal csr_wdata            : unsigned(31 downto 0) := (others => '0');
    signal csr_rdata            : unsigned(31 downto 0) := (others => '0');
    signal csr_uid              : unsigned(31 downto 0) := to_unsigned(16#2604#, 32);
    signal csr_status           : unsigned(31 downto 0) := (others => '0');
    signal csr_lane_mask_shadow : unsigned(3 downto 0) := (others => '0');
    signal csr_ft_wr_header     : unsigned(31 downto 0) := (others => '0');
    signal csr_ft_wr_subheader  : unsigned(31 downto 0) := (others => '0');
    signal csr_ft_wr_hit        : unsigned(31 downto 0) := (others => '0');
    signal csr_ft_rd_header     : unsigned(31 downto 0) := (others => '0');
    signal csr_ft_rd_subheader  : unsigned(31 downto 0) := (others => '0');
    signal csr_ft_rd_hit        : unsigned(31 downto 0) := (others => '0');
    signal csr_ft_drop_header   : unsigned(31 downto 0) := (others => '0');
    signal csr_ft_drop_subheader : unsigned(31 downto 0) := (others => '0');
    signal csr_ft_drop_hit      : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_wr_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_wr_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_wr_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_rd_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_rd_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_rd_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_drop_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_drop_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_drop_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_wr_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_wr_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_wr_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_rd_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_rd_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_rd_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_drop_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_drop_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_drop_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_wr_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_wr_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_wr_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_rd_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_rd_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_rd_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_drop_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_drop_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_drop_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_wr_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_wr_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_wr_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_rd_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_rd_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_rd_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_drop_hdr_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_drop_shd_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_drop_hit_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_accept_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_accept_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_accept_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_accept_cnt : unsigned(31 downto 0) := (others => '0');
    signal csr_lane0_drop_cnt   : unsigned(31 downto 0) := (others => '0');
    signal csr_lane1_drop_cnt   : unsigned(31 downto 0) := (others => '0');
    signal csr_lane2_drop_cnt   : unsigned(31 downto 0) := (others => '0');
    signal csr_lane3_drop_cnt   : unsigned(31 downto 0) := (others => '0');

    signal stat_offered_frame_count        : unsigned(31 downto 0) := (others => '0');
    signal stat_offered_subframe_count     : unsigned(31 downto 0) := (others => '0');
    signal stat_offered_hit_count          : unsigned(31 downto 0) := (others => '0');
    signal stat_ingress_frame_count        : unsigned(31 downto 0) := (others => '0');
    signal stat_ingress_subframe_count     : unsigned(31 downto 0) := (others => '0');
    signal stat_ingress_hit_count          : unsigned(31 downto 0) := (others => '0');
    signal stat_egress_frame_count         : unsigned(31 downto 0) := (others => '0');
    signal stat_egress_subframe_count      : unsigned(31 downto 0) := (others => '0');
    signal stat_egress_hit_count           : unsigned(31 downto 0) := (others => '0');
    signal stat_hit_inflight_count         : unsigned(31 downto 0) := (others => '0');
    signal stat_drop_controlled_frame      : unsigned(31 downto 0) := (others => '0');
    signal stat_drop_controlled_subframe   : unsigned(31 downto 0) := (others => '0');
    signal stat_drop_controlled_hit        : unsigned(31 downto 0) := (others => '0');
    signal stat_drop_asserted_frame        : unsigned(31 downto 0) := (others => '0');
    signal stat_drop_asserted_subframe     : unsigned(31 downto 0) := (others => '0');
    signal stat_drop_asserted_hit          : unsigned(31 downto 0) := (others => '0');
    signal stat_drop_inferred_frame        : unsigned(31 downto 0) := (others => '0');
    signal stat_drop_inferred_subframe     : unsigned(31 downto 0) := (others => '0');
    signal stat_drop_inferred_hit          : unsigned(31 downto 0) := (others => '0');
    signal stat_lane_fifo_total_usedw      : unsigned(15 downto 0) := (others => '0');
    signal stat_lane_fifo_max_usedw        : unsigned(10 downto 0) := (others => '0');
    signal stat_ticket_fifo_total_usedw    : unsigned(15 downto 0) := (others => '0');
    signal stat_ticket_fifo_max_usedw      : unsigned(10 downto 0) := (others => '0');
    signal stat_page_ram_max_usedw         : unsigned(15 downto 0) := (others => '0');

    signal error_expected    : std_logic := '0';
    signal ghost_count       : unsigned(15 downto 0) := (others => '0');
    signal missing_count     : unsigned(15 downto 0) := (others => '0');
    signal scoreboard_pass   : std_logic := '0';

    function count_ones(constant value : std_logic_vector) return natural is
        variable count : natural := 0;
    begin
        for idx in value'range loop
            if value(idx) = '1' then
                count := count + 1;
            end if;
        end loop;
        return count;
    end function;

    function fifo_usedw(
        constant wr_ptr : natural;
        constant rd_ptr : natural;
        constant depth  : natural
    ) return natural is
    begin
        if wr_ptr >= rd_ptr then
            return wr_ptr - rd_ptr;
        end if;
        return depth - rd_ptr + wr_ptr;
    end function;

    function sat_sub(
        constant left_value  : natural;
        constant right_value : natural
    ) return natural is
    begin
        if left_value > right_value then
            return left_value - right_value;
        end if;
        return 0;
    end function;

    function bucket_name(constant bucket : natural) return string is
    begin
        case bucket is
            when C_BUCKET_BASIC => return "BASIC";
            when C_BUCKET_PROF  => return "PROF";
            when C_BUCKET_ERROR => return "ERROR";
            when C_BUCKET_CSR   => return "CSR";
            when others => return "UNKNOWN";
        end case;
    end function;

    function case_name(constant code : natural) return string is
    begin
        case code is
            when 1    => return "B001";
            when 46   => return "B046";
            when 2123 => return "P123";
            when 3111 => return "X111";
            when 4001 => return "C001";
            when others => return "UNKNOWN";
        end case;
    end function;

    function runtime_mask_for_case(
        constant cfg  : t_case_cfg;
        constant tick : natural
    ) return t_lane_mask is
        variable frame_idx_v : natural;
    begin
        frame_idx_v := tick / C_FRAME_PERIOD_CYCLES;
        if cfg.code = 46 then
            if frame_idx_v = 0 then
                return "1111";
            elsif frame_idx_v = 1 then
                return "0011";
            else
                return "0001";
            end if;
        elsif cfg.code = 4001 then
            if frame_idx_v = 1 then
                return "1011";
            else
                return "1111";
            end if;
        end if;
        return "1111";
    end function;

    function replay_path(
        constant case_id : string;
        constant leaf    : string
    ) return string is
    begin
        return "replay/" & case_id & "/" & leaf & ".mem";
    end function;

    function ev_source_lane(constant raw : t_event_word) return natural is
    begin
        return to_integer(unsigned(raw(46 downto 45)));
    end function;

    function ev_kind(constant raw : t_event_word) return natural is
    begin
        return to_integer(unsigned(raw(44 downto 40)));
    end function;

    function ev_valid(constant raw : t_event_word) return std_logic is
    begin
        return raw(36);
    end function;

    function ev_datak(constant raw : t_event_word) return t_datak_word is
    begin
        return raw(35 downto 32);
    end function;

    function ev_data(constant raw : t_event_word) return t_data_word is
    begin
        return raw(31 downto 0);
    end function;

    function is_ticket_kind(constant kind : natural) return boolean is
    begin
        return kind = C_KIND_SOP_HEADER or kind = C_KIND_HEADER_ERROR
            or kind = C_KIND_SUBHEADER or kind = C_KIND_SUBHEADER_ERROR;
    end function;

    function is_header_kind(constant kind : natural) return boolean is
    begin
        return kind = C_KIND_SOP_HEADER or kind = C_KIND_HEADER_ERROR;
    end function;

    function is_subheader_kind(constant kind : natural) return boolean is
    begin
        return kind = C_KIND_SUBHEADER or kind = C_KIND_SUBHEADER_ERROR;
    end function;

    function is_hit_kind(constant kind : natural) return boolean is
    begin
        return kind = C_KIND_HIT or kind = C_KIND_HIT_ERROR;
    end function;

    function is_error_kind(constant kind : natural) return boolean is
    begin
        return kind = C_KIND_HEADER_ERROR
            or kind = C_KIND_SUBHEADER_ERROR
            or kind = C_KIND_HIT_ERROR;
    end function;

    procedure read_event(
        file f       : text;
        variable raw : out t_event_word
    ) is
        variable line_v : line;
    begin
        if endfile(f) then
            raw := (others => '0');
        else
            readline(f, line_v);
            hread(line_v, raw);
        end if;
    end procedure;

    procedure drive_event(
        signal data_s        : out t_data_word;
        signal datak_s       : out t_datak_word;
        signal kind_s        : out t_word_kind;
        signal header_id_s   : out t_header_id;
        signal source_lane_s : out t_lane_id;
        signal frame_ts_s    : out t_timestamp;
        signal hit_low_s     : out t_halfword;
        variable state_v     : inout t_ts_state;
        constant raw         : in t_event_word
    ) is
        variable data_v : t_data_word;
        variable kind_v : natural;
    begin
        data_v := ev_data(raw);
        kind_v := ev_kind(raw);
        if ev_valid(raw) = '0' then
            data_v := (others => '0');
            kind_v := C_KIND_IDLE;
        end if;

        if kind_v = C_KIND_TS_HIGH then
            state_v.ts_high := unsigned(data_v);
        elsif kind_v = C_KIND_TS_LOW_PKG then
            state_v.ts_low := unsigned(data_v(31 downto 16));
        end if;

        data_s <= data_v;
        datak_s <= ev_datak(raw) when ev_valid(raw) = '1' else (others => '0');
        kind_s <= to_unsigned(kind_v, kind_s'length);
        header_id_s <= unsigned(data_v(31 downto 26));
        source_lane_s <= to_unsigned(ev_source_lane(raw), source_lane_s'length);
        frame_ts_s <= state_v.ts_high & state_v.ts_low;
        hit_low_s <= unsigned(data_v(15 downto 0));
    end procedure;

begin

    clk <= not clk after C_CLK_PERIOD / 2;
    lane0_word <= lane0_datak & lane0_data;
    lane1_word <= lane1_datak & lane1_data;
    lane2_word <= lane2_datak & lane2_data;
    lane3_word <= lane3_datak & lane3_data;
    opq_word <= opq_datak & opq_data;
    dma_word <= dma_datak & dma_data;

    proc_cross_run : process
        file lane0_file : text;
        file lane1_file : text;
        file lane2_file : text;
        file lane3_file : text;
        file opq_file   : text;
        variable cfg             : t_case_cfg;
        variable raw0_v          : t_event_word;
        variable raw1_v          : t_event_word;
        variable raw2_v          : t_event_word;
        variable raw3_v          : t_event_word;
        variable raw_opq_v       : t_event_word;
        variable lane_state_v    : t_nat4 := (0, 0, 0, 0);
        variable ticket_state_v  : t_nat4 := (0, 0, 0, 0);
        variable lane_wr_ptr_v   : t_nat4 := (0, 0, 0, 0);
        variable lane_rd_ptr_v   : t_nat4 := (0, 0, 0, 0);
        variable ticket_wr_ptr_v : t_nat4 := (0, 0, 0, 0);
        variable ticket_rd_ptr_v : t_nat4 := (0, 0, 0, 0);
        variable lane_drain_v    : t_nat4 := (0, 0, 0, 0);
        variable ticket_drain_v  : t_nat4 := (0, 0, 0, 0);
        variable lane_credit_v   : t_nat4 := (C_LANE_FIFO_MAX_CREDIT, C_LANE_FIFO_MAX_CREDIT, C_LANE_FIFO_MAX_CREDIT, C_LANE_FIFO_MAX_CREDIT);
        variable ticket_credit_v : t_nat4 := (C_TICKET_FIFO_MAX_CREDIT, C_TICKET_FIFO_MAX_CREDIT, C_TICKET_FIFO_MAX_CREDIT, C_TICKET_FIFO_MAX_CREDIT);
        variable lane_accept_v   : t_nat4 := (0, 0, 0, 0);
        variable lane_drop_v     : t_nat4 := (0, 0, 0, 0);
        variable lane_wr_hdr_v   : t_nat4 := (0, 0, 0, 0);
        variable lane_wr_shd_v   : t_nat4 := (0, 0, 0, 0);
        variable lane_wr_hit_v   : t_nat4 := (0, 0, 0, 0);
        variable lane_rd_hdr_v   : t_nat4 := (0, 0, 0, 0);
        variable lane_rd_shd_v   : t_nat4 := (0, 0, 0, 0);
        variable lane_rd_hit_v   : t_nat4 := (0, 0, 0, 0);
        variable lane_drop_hdr_v : t_nat4 := (0, 0, 0, 0);
        variable lane_drop_shd_v : t_nat4 := (0, 0, 0, 0);
        variable lane_drop_hit_v : t_nat4 := (0, 0, 0, 0);
        variable drr_quantum_v   : t_nat4 := (C_DRR_DEFAULT_ALLOWANCE, C_DRR_DEFAULT_ALLOWANCE, C_DRR_DEFAULT_ALLOWANCE, C_DRR_DEFAULT_ALLOWANCE);
        variable drr_grant_cnt_v : t_nat4 := (0, 0, 0, 0);
        variable drr_beat_cnt_v  : t_nat4 := (0, 0, 0, 0);
        variable drr_defer_cnt_v : t_nat4 := (0, 0, 0, 0);
        variable lane_head_word_v : t_stream_word4 := ((others => '0'), (others => '0'), (others => '0'), (others => '0'));
        variable lane_head_kind_v : t_nat4 := (0, 0, 0, 0);
        variable lane_ts0_v      : t_ts_state := ((others => '0'), (others => '0'));
        variable lane_ts1_v      : t_ts_state := ((others => '0'), (others => '0'));
        variable lane_ts2_v      : t_ts_state := ((others => '0'), (others => '0'));
        variable lane_ts3_v      : t_ts_state := ((others => '0'), (others => '0'));
        variable opq_ts_v        : t_ts_state := ((others => '0'), (others => '0'));
        variable dma_ts_v        : t_ts_state := ((others => '0'), (others => '0'));
        variable valid_v         : std_logic_vector(3 downto 0);
        variable fire_v          : std_logic_vector(3 downto 0);
        variable ticket_push_v   : std_logic_vector(3 downto 0);
        variable alloc_req_v     : std_logic_vector(3 downto 0);
        variable alloc_grant_lane_v : std_logic_vector(3 downto 0);
        variable drr_req_raw_v   : std_logic_vector(3 downto 0);
        variable drr_req_eligible_v : std_logic_vector(3 downto 0);
        variable drr_grant_v     : std_logic_vector(3 downto 0);
        variable drr_defer_v     : std_logic_vector(3 downto 0);
        variable lane_kind_v      : t_nat4 := (0, 0, 0, 0);
        variable lane_packet_done_v : std_logic_vector(3 downto 0) := (others => '1');
        variable lane_packet_open_v : std_logic_vector(3 downto 0) := (others => '0');
        variable page_commit_open_v : boolean := false;
        variable active_mask_v   : t_lane_mask;
        variable ingress_count_v : natural := 0;
        variable opq_count_v     : natural := 0;
        variable payload_count_v : natural := 0;
        variable dma_count_v     : natural := 0;
        variable handle_usedw_v  : natural := 0;
        variable handle_drain_v  : natural := 0;
        variable page_usedw_v    : natural := 0;
        variable ticket_id_v     : natural := 0;
        variable selected_lane_v : natural := 0;
        variable candidate_lane_v : natural := 0;
        variable alloc_lane_v    : natural := 0;
        variable drr_selected_lane_v : natural := 0;
        variable allocator_rr_v  : natural := 0;
        variable drr_rr_v        : natural := 0;
        variable drr_lane_v      : natural := 0;
        variable opq_lane_v      : natural := 0;
        variable opq_kind_v      : natural := 0;
        variable dma_half_full_v : std_logic;
        variable join_pending_v  : std_logic;
        variable page_write_v    : std_logic;
        variable page_inc_v      : natural := 0;
        variable ft_wr_header_v  : natural := 0;
        variable ft_wr_subh_v    : natural := 0;
        variable ft_wr_hit_v     : natural := 0;
        variable ft_rd_header_v  : natural := 0;
        variable ft_rd_subh_v    : natural := 0;
        variable ft_rd_hit_v     : natural := 0;
        variable ft_drop_header_v : natural := 0;
        variable ft_drop_subh_v  : natural := 0;
        variable ft_drop_hit_v   : natural := 0;
        variable stat_offered_frame_v      : natural := 0;
        variable stat_offered_subframe_v   : natural := 0;
        variable stat_offered_hit_v        : natural := 0;
        variable stat_ingress_frame_v      : natural := 0;
        variable stat_ingress_subframe_v   : natural := 0;
        variable stat_ingress_hit_v        : natural := 0;
        variable stat_egress_frame_v       : natural := 0;
        variable stat_egress_subframe_v    : natural := 0;
        variable stat_egress_hit_v         : natural := 0;
        variable stat_hit_inflight_v       : natural := 0;
        variable stat_drop_controlled_frame_v    : natural := 0;
        variable stat_drop_controlled_subframe_v : natural := 0;
        variable stat_drop_controlled_hit_v      : natural := 0;
        variable stat_drop_asserted_frame_v      : natural := 0;
        variable stat_drop_asserted_subframe_v   : natural := 0;
        variable stat_drop_asserted_hit_v        : natural := 0;
        variable stat_drop_inferred_frame_v      : natural := 0;
        variable stat_drop_inferred_subframe_v   : natural := 0;
        variable stat_drop_inferred_hit_v        : natural := 0;
        variable stat_lane_fifo_total_usedw_v    : natural := 0;
        variable stat_lane_fifo_max_usedw_v      : natural := 0;
        variable stat_ticket_fifo_total_usedw_v  : natural := 0;
        variable stat_ticket_fifo_max_usedw_v    : natural := 0;
        variable stat_page_ram_max_usedw_v       : natural := 0;
        variable csr_step_v      : natural := 0;
        variable csr_lane_v      : natural := 0;
        variable csr_lane_word_v : natural := 0;
        variable csr_status_v    : unsigned(31 downto 0);

        procedure sync_fifo_signals is
        begin
            for lane in 0 to 3 loop
                lane_state_v(lane) := fifo_usedw(lane_wr_ptr_v(lane), lane_rd_ptr_v(lane), C_LANE_FIFO_DEPTH);
                ticket_state_v(lane) := fifo_usedw(ticket_wr_ptr_v(lane), ticket_rd_ptr_v(lane), C_TICKET_FIFO_DEPTH);
            end loop;
            opq_lane0_fifo_usedw <= to_unsigned(lane_state_v(0), opq_lane0_fifo_usedw'length);
            opq_lane1_fifo_usedw <= to_unsigned(lane_state_v(1), opq_lane1_fifo_usedw'length);
            opq_lane2_fifo_usedw <= to_unsigned(lane_state_v(2), opq_lane2_fifo_usedw'length);
            opq_lane3_fifo_usedw <= to_unsigned(lane_state_v(3), opq_lane3_fifo_usedw'length);
            opq_lane0_fifo_wr_ptr <= to_unsigned(lane_wr_ptr_v(0), opq_lane0_fifo_wr_ptr'length);
            opq_lane1_fifo_wr_ptr <= to_unsigned(lane_wr_ptr_v(1), opq_lane1_fifo_wr_ptr'length);
            opq_lane2_fifo_wr_ptr <= to_unsigned(lane_wr_ptr_v(2), opq_lane2_fifo_wr_ptr'length);
            opq_lane3_fifo_wr_ptr <= to_unsigned(lane_wr_ptr_v(3), opq_lane3_fifo_wr_ptr'length);
            opq_lane0_fifo_rd_ptr <= to_unsigned(lane_rd_ptr_v(0), opq_lane0_fifo_rd_ptr'length);
            opq_lane1_fifo_rd_ptr <= to_unsigned(lane_rd_ptr_v(1), opq_lane1_fifo_rd_ptr'length);
            opq_lane2_fifo_rd_ptr <= to_unsigned(lane_rd_ptr_v(2), opq_lane2_fifo_rd_ptr'length);
            opq_lane3_fifo_rd_ptr <= to_unsigned(lane_rd_ptr_v(3), opq_lane3_fifo_rd_ptr'length);
            opq_ticket0_fifo_usedw <= to_unsigned(ticket_state_v(0), opq_ticket0_fifo_usedw'length);
            opq_ticket1_fifo_usedw <= to_unsigned(ticket_state_v(1), opq_ticket1_fifo_usedw'length);
            opq_ticket2_fifo_usedw <= to_unsigned(ticket_state_v(2), opq_ticket2_fifo_usedw'length);
            opq_ticket3_fifo_usedw <= to_unsigned(ticket_state_v(3), opq_ticket3_fifo_usedw'length);
            opq_ticket0_fifo_wr_ptr <= to_unsigned(ticket_wr_ptr_v(0), opq_ticket0_fifo_wr_ptr'length);
            opq_ticket1_fifo_wr_ptr <= to_unsigned(ticket_wr_ptr_v(1), opq_ticket1_fifo_wr_ptr'length);
            opq_ticket2_fifo_wr_ptr <= to_unsigned(ticket_wr_ptr_v(2), opq_ticket2_fifo_wr_ptr'length);
            opq_ticket3_fifo_wr_ptr <= to_unsigned(ticket_wr_ptr_v(3), opq_ticket3_fifo_wr_ptr'length);
            opq_ticket0_fifo_rd_ptr <= to_unsigned(ticket_rd_ptr_v(0), opq_ticket0_fifo_rd_ptr'length);
            opq_ticket1_fifo_rd_ptr <= to_unsigned(ticket_rd_ptr_v(1), opq_ticket1_fifo_rd_ptr'length);
            opq_ticket2_fifo_rd_ptr <= to_unsigned(ticket_rd_ptr_v(2), opq_ticket2_fifo_rd_ptr'length);
            opq_ticket3_fifo_rd_ptr <= to_unsigned(ticket_rd_ptr_v(3), opq_ticket3_fifo_rd_ptr'length);
            opq_lane0_credit <= to_unsigned(lane_credit_v(0), opq_lane0_credit'length);
            opq_lane1_credit <= to_unsigned(lane_credit_v(1), opq_lane1_credit'length);
            opq_lane2_credit <= to_unsigned(lane_credit_v(2), opq_lane2_credit'length);
            opq_lane3_credit <= to_unsigned(lane_credit_v(3), opq_lane3_credit'length);
            opq_ticket0_credit <= to_unsigned(ticket_credit_v(0), opq_ticket0_credit'length);
            opq_ticket1_credit <= to_unsigned(ticket_credit_v(1), opq_ticket1_credit'length);
            opq_ticket2_credit <= to_unsigned(ticket_credit_v(2), opq_ticket2_credit'length);
            opq_ticket3_credit <= to_unsigned(ticket_credit_v(3), opq_ticket3_credit'length);
            opq_drr_quantum0 <= to_unsigned(drr_quantum_v(0), opq_drr_quantum0'length);
            opq_drr_quantum1 <= to_unsigned(drr_quantum_v(1), opq_drr_quantum1'length);
            opq_drr_quantum2 <= to_unsigned(drr_quantum_v(2), opq_drr_quantum2'length);
            opq_drr_quantum3 <= to_unsigned(drr_quantum_v(3), opq_drr_quantum3'length);
            opq_handle_fifo_usedw <= to_unsigned(handle_usedw_v, opq_handle_fifo_usedw'length);
            opq_page_ram_usedw <= to_unsigned(page_usedw_v, opq_page_ram_usedw'length);
            opq_page_free_count <= to_unsigned(4096 - page_usedw_v, opq_page_free_count'length);
        end procedure;

        procedure sync_counter_signals is
        begin
            csr_ft_wr_header <= to_unsigned(ft_wr_header_v, csr_ft_wr_header'length);
            csr_ft_wr_subheader <= to_unsigned(ft_wr_subh_v, csr_ft_wr_subheader'length);
            csr_ft_wr_hit <= to_unsigned(ft_wr_hit_v, csr_ft_wr_hit'length);
            csr_ft_rd_header <= to_unsigned(ft_rd_header_v, csr_ft_rd_header'length);
            csr_ft_rd_subheader <= to_unsigned(ft_rd_subh_v, csr_ft_rd_subheader'length);
            csr_ft_rd_hit <= to_unsigned(ft_rd_hit_v, csr_ft_rd_hit'length);
            csr_ft_drop_header <= to_unsigned(ft_drop_header_v, csr_ft_drop_header'length);
            csr_ft_drop_subheader <= to_unsigned(ft_drop_subh_v, csr_ft_drop_subheader'length);
            csr_ft_drop_hit <= to_unsigned(ft_drop_hit_v, csr_ft_drop_hit'length);
            csr_lane0_wr_hdr_cnt <= to_unsigned(lane_wr_hdr_v(0), csr_lane0_wr_hdr_cnt'length);
            csr_lane0_wr_shd_cnt <= to_unsigned(lane_wr_shd_v(0), csr_lane0_wr_shd_cnt'length);
            csr_lane0_wr_hit_cnt <= to_unsigned(lane_wr_hit_v(0), csr_lane0_wr_hit_cnt'length);
            csr_lane0_rd_hdr_cnt <= to_unsigned(lane_rd_hdr_v(0), csr_lane0_rd_hdr_cnt'length);
            csr_lane0_rd_shd_cnt <= to_unsigned(lane_rd_shd_v(0), csr_lane0_rd_shd_cnt'length);
            csr_lane0_rd_hit_cnt <= to_unsigned(lane_rd_hit_v(0), csr_lane0_rd_hit_cnt'length);
            csr_lane0_drop_hdr_cnt <= to_unsigned(lane_drop_hdr_v(0), csr_lane0_drop_hdr_cnt'length);
            csr_lane0_drop_shd_cnt <= to_unsigned(lane_drop_shd_v(0), csr_lane0_drop_shd_cnt'length);
            csr_lane0_drop_hit_cnt <= to_unsigned(lane_drop_hit_v(0), csr_lane0_drop_hit_cnt'length);
            csr_lane1_wr_hdr_cnt <= to_unsigned(lane_wr_hdr_v(1), csr_lane1_wr_hdr_cnt'length);
            csr_lane1_wr_shd_cnt <= to_unsigned(lane_wr_shd_v(1), csr_lane1_wr_shd_cnt'length);
            csr_lane1_wr_hit_cnt <= to_unsigned(lane_wr_hit_v(1), csr_lane1_wr_hit_cnt'length);
            csr_lane1_rd_hdr_cnt <= to_unsigned(lane_rd_hdr_v(1), csr_lane1_rd_hdr_cnt'length);
            csr_lane1_rd_shd_cnt <= to_unsigned(lane_rd_shd_v(1), csr_lane1_rd_shd_cnt'length);
            csr_lane1_rd_hit_cnt <= to_unsigned(lane_rd_hit_v(1), csr_lane1_rd_hit_cnt'length);
            csr_lane1_drop_hdr_cnt <= to_unsigned(lane_drop_hdr_v(1), csr_lane1_drop_hdr_cnt'length);
            csr_lane1_drop_shd_cnt <= to_unsigned(lane_drop_shd_v(1), csr_lane1_drop_shd_cnt'length);
            csr_lane1_drop_hit_cnt <= to_unsigned(lane_drop_hit_v(1), csr_lane1_drop_hit_cnt'length);
            csr_lane2_wr_hdr_cnt <= to_unsigned(lane_wr_hdr_v(2), csr_lane2_wr_hdr_cnt'length);
            csr_lane2_wr_shd_cnt <= to_unsigned(lane_wr_shd_v(2), csr_lane2_wr_shd_cnt'length);
            csr_lane2_wr_hit_cnt <= to_unsigned(lane_wr_hit_v(2), csr_lane2_wr_hit_cnt'length);
            csr_lane2_rd_hdr_cnt <= to_unsigned(lane_rd_hdr_v(2), csr_lane2_rd_hdr_cnt'length);
            csr_lane2_rd_shd_cnt <= to_unsigned(lane_rd_shd_v(2), csr_lane2_rd_shd_cnt'length);
            csr_lane2_rd_hit_cnt <= to_unsigned(lane_rd_hit_v(2), csr_lane2_rd_hit_cnt'length);
            csr_lane2_drop_hdr_cnt <= to_unsigned(lane_drop_hdr_v(2), csr_lane2_drop_hdr_cnt'length);
            csr_lane2_drop_shd_cnt <= to_unsigned(lane_drop_shd_v(2), csr_lane2_drop_shd_cnt'length);
            csr_lane2_drop_hit_cnt <= to_unsigned(lane_drop_hit_v(2), csr_lane2_drop_hit_cnt'length);
            csr_lane3_wr_hdr_cnt <= to_unsigned(lane_wr_hdr_v(3), csr_lane3_wr_hdr_cnt'length);
            csr_lane3_wr_shd_cnt <= to_unsigned(lane_wr_shd_v(3), csr_lane3_wr_shd_cnt'length);
            csr_lane3_wr_hit_cnt <= to_unsigned(lane_wr_hit_v(3), csr_lane3_wr_hit_cnt'length);
            csr_lane3_rd_hdr_cnt <= to_unsigned(lane_rd_hdr_v(3), csr_lane3_rd_hdr_cnt'length);
            csr_lane3_rd_shd_cnt <= to_unsigned(lane_rd_shd_v(3), csr_lane3_rd_shd_cnt'length);
            csr_lane3_rd_hit_cnt <= to_unsigned(lane_rd_hit_v(3), csr_lane3_rd_hit_cnt'length);
            csr_lane3_drop_hdr_cnt <= to_unsigned(lane_drop_hdr_v(3), csr_lane3_drop_hdr_cnt'length);
            csr_lane3_drop_shd_cnt <= to_unsigned(lane_drop_shd_v(3), csr_lane3_drop_shd_cnt'length);
            csr_lane3_drop_hit_cnt <= to_unsigned(lane_drop_hit_v(3), csr_lane3_drop_hit_cnt'length);
            csr_lane0_accept_cnt <= to_unsigned(lane_accept_v(0), csr_lane0_accept_cnt'length);
            csr_lane1_accept_cnt <= to_unsigned(lane_accept_v(1), csr_lane1_accept_cnt'length);
            csr_lane2_accept_cnt <= to_unsigned(lane_accept_v(2), csr_lane2_accept_cnt'length);
            csr_lane3_accept_cnt <= to_unsigned(lane_accept_v(3), csr_lane3_accept_cnt'length);
            csr_lane0_drop_cnt <= to_unsigned(lane_drop_v(0), csr_lane0_drop_cnt'length);
            csr_lane1_drop_cnt <= to_unsigned(lane_drop_v(1), csr_lane1_drop_cnt'length);
            csr_lane2_drop_cnt <= to_unsigned(lane_drop_v(2), csr_lane2_drop_cnt'length);
            csr_lane3_drop_cnt <= to_unsigned(lane_drop_v(3), csr_lane3_drop_cnt'length);
        end procedure;

        procedure sync_stat_signals is
        begin
            stat_lane_fifo_total_usedw_v := 0;
            stat_lane_fifo_max_usedw_v := 0;
            stat_ticket_fifo_total_usedw_v := 0;
            stat_ticket_fifo_max_usedw_v := 0;
            for lane in 0 to 3 loop
                stat_lane_fifo_total_usedw_v := stat_lane_fifo_total_usedw_v + lane_state_v(lane);
                stat_ticket_fifo_total_usedw_v := stat_ticket_fifo_total_usedw_v + ticket_state_v(lane);
                if lane_state_v(lane) > stat_lane_fifo_max_usedw_v then
                    stat_lane_fifo_max_usedw_v := lane_state_v(lane);
                end if;
                if ticket_state_v(lane) > stat_ticket_fifo_max_usedw_v then
                    stat_ticket_fifo_max_usedw_v := ticket_state_v(lane);
                end if;
            end loop;
            if page_usedw_v > stat_page_ram_max_usedw_v then
                stat_page_ram_max_usedw_v := page_usedw_v;
            end if;
            stat_hit_inflight_v := sat_sub(stat_ingress_hit_v, stat_egress_hit_v);

            stat_offered_frame_count <= to_unsigned(stat_offered_frame_v, stat_offered_frame_count'length);
            stat_offered_subframe_count <= to_unsigned(stat_offered_subframe_v, stat_offered_subframe_count'length);
            stat_offered_hit_count <= to_unsigned(stat_offered_hit_v, stat_offered_hit_count'length);
            stat_ingress_frame_count <= to_unsigned(stat_ingress_frame_v, stat_ingress_frame_count'length);
            stat_ingress_subframe_count <= to_unsigned(stat_ingress_subframe_v, stat_ingress_subframe_count'length);
            stat_ingress_hit_count <= to_unsigned(stat_ingress_hit_v, stat_ingress_hit_count'length);
            stat_egress_frame_count <= to_unsigned(stat_egress_frame_v, stat_egress_frame_count'length);
            stat_egress_subframe_count <= to_unsigned(stat_egress_subframe_v, stat_egress_subframe_count'length);
            stat_egress_hit_count <= to_unsigned(stat_egress_hit_v, stat_egress_hit_count'length);
            stat_hit_inflight_count <= to_unsigned(stat_hit_inflight_v, stat_hit_inflight_count'length);
            stat_drop_controlled_frame <= to_unsigned(stat_drop_controlled_frame_v, stat_drop_controlled_frame'length);
            stat_drop_controlled_subframe <= to_unsigned(stat_drop_controlled_subframe_v, stat_drop_controlled_subframe'length);
            stat_drop_controlled_hit <= to_unsigned(stat_drop_controlled_hit_v, stat_drop_controlled_hit'length);
            stat_drop_asserted_frame <= to_unsigned(stat_drop_asserted_frame_v, stat_drop_asserted_frame'length);
            stat_drop_asserted_subframe <= to_unsigned(stat_drop_asserted_subframe_v, stat_drop_asserted_subframe'length);
            stat_drop_asserted_hit <= to_unsigned(stat_drop_asserted_hit_v, stat_drop_asserted_hit'length);
            stat_drop_inferred_frame <= to_unsigned(stat_drop_inferred_frame_v, stat_drop_inferred_frame'length);
            stat_drop_inferred_subframe <= to_unsigned(stat_drop_inferred_subframe_v, stat_drop_inferred_subframe'length);
            stat_drop_inferred_hit <= to_unsigned(stat_drop_inferred_hit_v, stat_drop_inferred_hit'length);
            stat_lane_fifo_total_usedw <= to_unsigned(stat_lane_fifo_total_usedw_v, stat_lane_fifo_total_usedw'length);
            stat_lane_fifo_max_usedw <= to_unsigned(stat_lane_fifo_max_usedw_v, stat_lane_fifo_max_usedw'length);
            stat_ticket_fifo_total_usedw <= to_unsigned(stat_ticket_fifo_total_usedw_v, stat_ticket_fifo_total_usedw'length);
            stat_ticket_fifo_max_usedw <= to_unsigned(stat_ticket_fifo_max_usedw_v, stat_ticket_fifo_max_usedw'length);
            stat_page_ram_max_usedw <= to_unsigned(stat_page_ram_max_usedw_v, stat_page_ram_max_usedw'length);
        end procedure;

        procedure count_kind(
            constant kind       : in natural;
            variable frames     : inout natural;
            variable subframes  : inout natural;
            variable hits       : inout natural
        ) is
        begin
            if is_header_kind(kind) then
                frames := frames + 1;
            elsif is_subheader_kind(kind) then
                subframes := subframes + 1;
            elsif is_hit_kind(kind) then
                hits := hits + 1;
            end if;
        end procedure;

        procedure account_drop(
            constant raw          : in t_event_word;
            constant lane         : in natural;
            constant masked       : in boolean;
            variable lane_drop    : inout t_nat4;
            variable lane_drop_hdr : inout t_nat4;
            variable lane_drop_shd : inout t_nat4;
            variable lane_drop_hit : inout t_nat4;
            variable ft_drop_hdr  : inout natural;
            variable ft_drop_shd  : inout natural;
            variable ft_drop_hit  : inout natural;
            variable controlled_frame : inout natural;
            variable controlled_subframe : inout natural;
            variable controlled_hit : inout natural;
            variable asserted_frame : inout natural;
            variable asserted_subframe : inout natural;
            variable asserted_hit : inout natural
        ) is
            variable kind_v : natural;
        begin
            if ev_valid(raw) = '1' then
                kind_v := ev_kind(raw);
                if masked then
                    lane_drop(lane) := lane_drop(lane) + 1;
                    if is_header_kind(kind_v) then
                        lane_drop_hdr(lane) := lane_drop_hdr(lane) + 1;
                        controlled_frame := controlled_frame + 1;
                    elsif is_subheader_kind(kind_v) then
                        lane_drop_shd(lane) := lane_drop_shd(lane) + 1;
                        controlled_subframe := controlled_subframe + 1;
                    elsif is_hit_kind(kind_v) then
                        lane_drop_hit(lane) := lane_drop_hit(lane) + 1;
                        controlled_hit := controlled_hit + 1;
                    end if;
                elsif is_error_kind(kind_v) then
                    lane_drop(lane) := lane_drop(lane) + 1;
                    if is_header_kind(kind_v) then
                        lane_drop_hdr(lane) := lane_drop_hdr(lane) + 1;
                        ft_drop_hdr := ft_drop_hdr + 1;
                        asserted_frame := asserted_frame + 1;
                    elsif is_subheader_kind(kind_v) then
                        lane_drop_shd(lane) := lane_drop_shd(lane) + 1;
                        ft_drop_shd := ft_drop_shd + 1;
                        asserted_subframe := asserted_subframe + 1;
                    elsif is_hit_kind(kind_v) then
                        lane_drop_hit(lane) := lane_drop_hit(lane) + 1;
                        ft_drop_hit := ft_drop_hit + 1;
                        asserted_hit := asserted_hit + 1;
                    end if;
                end if;
            end if;
        end procedure;

    begin
        reset_n <= '0';
        run_active <= '0';
        flow_state <= to_unsigned(0, flow_state'length);
        lane_ready <= (others => '1');

        for idx in 0 to 7 loop
            wait until rising_edge(clk);
            cycle_tick <= cycle_tick + 1;
        end loop;

        reset_n <= '1';
        run_active <= '1';
        report "[GHDL_CROSS_START] source=uvm_replay cases="
            & integer'image(C_CASES'length)
            & " case_cycles=" & integer'image(G_CASE_CYCLES)
            & " frame_period_cycles=" & integer'image(C_FRAME_PERIOD_CYCLES)
            & " frame_ts_step_8ns=0x800"
            severity note;

        for idx in C_CASES'range loop
            cfg := C_CASES(idx);
            ingress_count_v := 0;
            opq_count_v := 0;
            payload_count_v := 0;
            dma_count_v := 0;
            lane_state_v := (0, 0, 0, 0);
            ticket_state_v := (0, 0, 0, 0);
            lane_wr_ptr_v := (0, 0, 0, 0);
            lane_rd_ptr_v := (0, 0, 0, 0);
            ticket_wr_ptr_v := (0, 0, 0, 0);
            ticket_rd_ptr_v := (0, 0, 0, 0);
            lane_drain_v := (0, 0, 0, 0);
            ticket_drain_v := (0, 0, 0, 0);
            lane_credit_v := (C_LANE_FIFO_MAX_CREDIT, C_LANE_FIFO_MAX_CREDIT, C_LANE_FIFO_MAX_CREDIT, C_LANE_FIFO_MAX_CREDIT);
            ticket_credit_v := (C_TICKET_FIFO_MAX_CREDIT, C_TICKET_FIFO_MAX_CREDIT, C_TICKET_FIFO_MAX_CREDIT, C_TICKET_FIFO_MAX_CREDIT);
            lane_accept_v := (0, 0, 0, 0);
            lane_drop_v := (0, 0, 0, 0);
            lane_wr_hdr_v := (0, 0, 0, 0);
            lane_wr_shd_v := (0, 0, 0, 0);
            lane_wr_hit_v := (0, 0, 0, 0);
            lane_rd_hdr_v := (0, 0, 0, 0);
            lane_rd_shd_v := (0, 0, 0, 0);
            lane_rd_hit_v := (0, 0, 0, 0);
            lane_drop_hdr_v := (0, 0, 0, 0);
            lane_drop_shd_v := (0, 0, 0, 0);
            lane_drop_hit_v := (0, 0, 0, 0);
            drr_quantum_v := (C_DRR_DEFAULT_ALLOWANCE, C_DRR_DEFAULT_ALLOWANCE, C_DRR_DEFAULT_ALLOWANCE, C_DRR_DEFAULT_ALLOWANCE);
            drr_grant_cnt_v := (0, 0, 0, 0);
            drr_beat_cnt_v := (0, 0, 0, 0);
            drr_defer_cnt_v := (0, 0, 0, 0);
            lane_head_word_v := ((others => '0'), (others => '0'), (others => '0'), (others => '0'));
            lane_head_kind_v := (0, 0, 0, 0);
            lane_packet_done_v := (others => '1');
            lane_packet_open_v := (others => '0');
            page_commit_open_v := false;
            lane_ts0_v := ((others => '0'), (others => '0'));
            lane_ts1_v := ((others => '0'), (others => '0'));
            lane_ts2_v := ((others => '0'), (others => '0'));
            lane_ts3_v := ((others => '0'), (others => '0'));
            opq_ts_v := ((others => '0'), (others => '0'));
            dma_ts_v := ((others => '0'), (others => '0'));
            handle_usedw_v := 0;
            handle_drain_v := 0;
            page_usedw_v := 0;
            ticket_id_v := 0;
            allocator_rr_v := 0;
            drr_rr_v := 0;
            ft_wr_header_v := 0;
            ft_wr_subh_v := 0;
            ft_wr_hit_v := 0;
            ft_rd_header_v := 0;
            ft_rd_subh_v := 0;
            ft_rd_hit_v := 0;
            ft_drop_header_v := 0;
            ft_drop_subh_v := 0;
            ft_drop_hit_v := 0;
            stat_offered_frame_v := 0;
            stat_offered_subframe_v := 0;
            stat_offered_hit_v := 0;
            stat_ingress_frame_v := 0;
            stat_ingress_subframe_v := 0;
            stat_ingress_hit_v := 0;
            stat_egress_frame_v := 0;
            stat_egress_subframe_v := 0;
            stat_egress_hit_v := 0;
            stat_hit_inflight_v := 0;
            stat_drop_controlled_frame_v := 0;
            stat_drop_controlled_subframe_v := 0;
            stat_drop_controlled_hit_v := 0;
            stat_drop_asserted_frame_v := 0;
            stat_drop_asserted_subframe_v := 0;
            stat_drop_asserted_hit_v := 0;
            stat_drop_inferred_frame_v := 0;
            stat_drop_inferred_subframe_v := 0;
            stat_drop_inferred_hit_v := 0;
            stat_lane_fifo_total_usedw_v := 0;
            stat_lane_fifo_max_usedw_v := 0;
            stat_ticket_fifo_total_usedw_v := 0;
            stat_ticket_fifo_max_usedw_v := 0;
            stat_page_ram_max_usedw_v := 0;

            file_open(lane0_file, replay_path(case_name(cfg.code), "lane0"), read_mode);
            file_open(lane1_file, replay_path(case_name(cfg.code), "lane1"), read_mode);
            file_open(lane2_file, replay_path(case_name(cfg.code), "lane2"), read_mode);
            file_open(lane3_file, replay_path(case_name(cfg.code), "lane3"), read_mode);
            file_open(opq_file, replay_path(case_name(cfg.code), "opq"), read_mode);

            case_index <= to_unsigned(idx, case_index'length);
            bucket_id <= to_unsigned(cfg.bucket, bucket_id'length);
            case_code <= to_unsigned(cfg.code, case_code'length);
            expected_words <= (others => '0');
            error_expected <= '1' when cfg.error_path else '0';
            scoreboard_pass <= '0';

            report "[GHDL_CASE_BEGIN] idx=" & integer'image(idx)
                & " case=" & case_name(cfg.code)
                & " bucket=" & bucket_name(cfg.bucket)
                & " stimulus=uvm_reference_schedule"
                severity note;

            for tick in 0 to G_CASE_CYCLES - 1 loop
                wait until rising_edge(clk);
                cycle_tick <= cycle_tick + 1;
                case_tick <= to_unsigned(tick, case_tick'length);

                read_event(lane0_file, raw0_v);
                read_event(lane1_file, raw1_v);
                read_event(lane2_file, raw2_v);
                read_event(lane3_file, raw3_v);
                read_event(opq_file, raw_opq_v);
                lane_kind_v := (ev_kind(raw0_v), ev_kind(raw1_v), ev_kind(raw2_v), ev_kind(raw3_v));

                active_mask_v := runtime_mask_for_case(cfg, tick);
                lane_mask <= active_mask_v;
                csr_lane_mask_shadow <= unsigned(active_mask_v);

                case_sop <= '1' when tick = 0 else '0';
                segment_reset <= '1' when tick = 0 else '0';
                bucket_transition <= '1' when tick = 0 else '0';
                case_eop <= '1' when tick = G_CASE_CYCLES - 1 else '0';
                frame_slot <= '1' when (tick mod C_FRAME_PERIOD_CYCLES) = 0 else '0';

                lane_mask_cmd_valid <= '0';
                lane_mask_cmd_value <= active_mask_v;
                if cfg.code = 46 and (tick = C_FRAME_PERIOD_CYCLES or tick = 2 * C_FRAME_PERIOD_CYCLES) then
                    lane_mask_cmd_valid <= '1';
                end if;

                csr_cmd_valid <= '0';
                csr_cmd_write <= '0';
                csr_read_valid <= '0';
                csr_readdatavalid <= '0';
                csr_wdata <= (others => '0');
                csr_reg_id <= to_unsigned(C_CSR_NONE, csr_reg_id'length);
                csr_addr <= (others => '0');
                csr_rdata <= (others => '0');
                if cfg.code = 46 and (tick = C_FRAME_PERIOD_CYCLES or tick = 2 * C_FRAME_PERIOD_CYCLES) then
                    csr_cmd_valid <= '1';
                    csr_cmd_write <= '1';
                    csr_reg_id <= to_unsigned(C_CSR_LANE_MASK, csr_reg_id'length);
                    csr_addr <= to_unsigned(C_CSR_LANE_MASK_ADDR, csr_addr'length);
                    csr_wdata <= resize(unsigned(active_mask_v), csr_wdata'length);
                elsif cfg.csr_activity and (tick mod 256) = 64 then
                    csr_cmd_valid <= '1';
                    csr_read_valid <= '1';
                    csr_readdatavalid <= '1';
                    csr_step_v := (tick / 256) mod C_CSR_READ_STEPS;
                    case csr_step_v is
                        when 0 =>
                            csr_reg_id <= to_unsigned(C_CSR_UID, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_UID_ADDR, csr_addr'length);
                            csr_rdata <= to_unsigned(16#4F50514D#, csr_rdata'length);
                        when 1 =>
                            csr_reg_id <= to_unsigned(C_CSR_META, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_META_ADDR, csr_addr'length);
                            csr_rdata <= to_unsigned(16#1A04D1AC#, csr_rdata'length);
                        when 2 =>
                            csr_reg_id <= to_unsigned(C_CSR_LANE_MASK, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_LANE_MASK_ADDR, csr_addr'length);
                            csr_rdata <= resize(unsigned(active_mask_v), csr_rdata'length);
                        when 3 =>
                            csr_reg_id <= to_unsigned(C_CSR_CTRL, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_CTRL_ADDR, csr_addr'length);
                            csr_rdata <= (others => '0');
                        when 4 =>
                            csr_reg_id <= to_unsigned(C_CSR_STATUS, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_STATUS_ADDR, csr_addr'length);
                            csr_rdata <= csr_status;
                        when 5 =>
                            csr_reg_id <= to_unsigned(C_CSR_CAP, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_CAP_ADDR, csr_addr'length);
                            csr_rdata <= to_unsigned(16#0410401F#, csr_rdata'length);
                        when 6 =>
                            csr_reg_id <= to_unsigned(C_CSR_FT_WR_HDR, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_FT_BASE_ADDR + 0 * 4, csr_addr'length);
                            csr_rdata <= to_unsigned(ft_wr_header_v, csr_rdata'length);
                        when 7 =>
                            csr_reg_id <= to_unsigned(C_CSR_FT_WR_SHD, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_FT_BASE_ADDR + 1 * 4, csr_addr'length);
                            csr_rdata <= to_unsigned(ft_wr_subh_v, csr_rdata'length);
                        when 8 =>
                            csr_reg_id <= to_unsigned(C_CSR_FT_WR_HIT, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_FT_BASE_ADDR + 2 * 4, csr_addr'length);
                            csr_rdata <= to_unsigned(ft_wr_hit_v, csr_rdata'length);
                        when 9 =>
                            csr_reg_id <= to_unsigned(C_CSR_FT_RD_HDR, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_FT_BASE_ADDR + 3 * 4, csr_addr'length);
                            csr_rdata <= to_unsigned(ft_rd_header_v, csr_rdata'length);
                        when 10 =>
                            csr_reg_id <= to_unsigned(C_CSR_FT_RD_SHD, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_FT_BASE_ADDR + 4 * 4, csr_addr'length);
                            csr_rdata <= to_unsigned(ft_rd_subh_v, csr_rdata'length);
                        when 11 =>
                            csr_reg_id <= to_unsigned(C_CSR_FT_RD_HIT, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_FT_BASE_ADDR + 5 * 4, csr_addr'length);
                            csr_rdata <= to_unsigned(ft_rd_hit_v, csr_rdata'length);
                        when 12 =>
                            csr_reg_id <= to_unsigned(C_CSR_FT_DROP_HDR, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_FT_BASE_ADDR + 6 * 4, csr_addr'length);
                            csr_rdata <= to_unsigned(ft_drop_header_v, csr_rdata'length);
                        when 13 =>
                            csr_reg_id <= to_unsigned(C_CSR_FT_DROP_SHD, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_FT_BASE_ADDR + 7 * 4, csr_addr'length);
                            csr_rdata <= to_unsigned(ft_drop_subh_v, csr_rdata'length);
                        when 14 =>
                            csr_reg_id <= to_unsigned(C_CSR_FT_DROP_HIT, csr_reg_id'length);
                            csr_addr <= to_unsigned(C_CSR_FT_BASE_ADDR + 8 * 4, csr_addr'length);
                            csr_rdata <= to_unsigned(ft_drop_hit_v, csr_rdata'length);
                        when others =>
                            csr_lane_v := (csr_step_v - 15) / 16;
                            csr_lane_word_v := (csr_step_v - 15) mod 16;
                            csr_addr <= to_unsigned(C_CSR_LANE_BASE_ADDR + csr_lane_v * C_CSR_LANE_STRIDE + csr_lane_word_v * 4, csr_addr'length);
                            csr_reg_id <= to_unsigned(C_CSR_LANE_WR_HDR + csr_lane_word_v, csr_reg_id'length);
                            case csr_lane_word_v is
                                when 0 => csr_rdata <= to_unsigned(lane_wr_hdr_v(csr_lane_v), csr_rdata'length);
                                when 1 => csr_rdata <= to_unsigned(lane_wr_shd_v(csr_lane_v), csr_rdata'length);
                                when 2 => csr_rdata <= to_unsigned(lane_wr_hit_v(csr_lane_v), csr_rdata'length);
                                when 3 => csr_rdata <= to_unsigned(lane_rd_hdr_v(csr_lane_v), csr_rdata'length);
                                when 4 => csr_rdata <= to_unsigned(lane_rd_shd_v(csr_lane_v), csr_rdata'length);
                                when 5 => csr_rdata <= to_unsigned(lane_rd_hit_v(csr_lane_v), csr_rdata'length);
                                when 6 => csr_rdata <= to_unsigned(lane_drop_hdr_v(csr_lane_v), csr_rdata'length);
                                when 7 => csr_rdata <= to_unsigned(lane_drop_shd_v(csr_lane_v), csr_rdata'length);
                                when 8 => csr_rdata <= to_unsigned(lane_drop_hit_v(csr_lane_v), csr_rdata'length);
                                when 9 => csr_rdata <= to_unsigned(lane_credit_v(csr_lane_v), csr_rdata'length);
                                when 10 => csr_rdata <= to_unsigned(ticket_credit_v(csr_lane_v), csr_rdata'length);
                                when 11 => csr_rdata <= to_unsigned(C_DRR_DEFAULT_ALLOWANCE, csr_rdata'length);
                                when 12 => csr_rdata <= to_unsigned(drr_quantum_v(csr_lane_v), csr_rdata'length);
                                when 13 => csr_rdata <= to_unsigned(drr_grant_cnt_v(csr_lane_v), csr_rdata'length);
                                when 14 => csr_rdata <= to_unsigned(drr_beat_cnt_v(csr_lane_v), csr_rdata'length);
                                when others => csr_rdata <= to_unsigned(drr_defer_cnt_v(csr_lane_v), csr_rdata'length);
                            end case;
                    end case;
                end if;

                dma_half_full_v := '0';
                if cfg.dma_bp_pct > 0 and (tick mod 100) < cfg.dma_bp_pct then
                    dma_half_full_v := '1';
                end if;
                dma_half_full <= dma_half_full_v;

                join_pending_v := '0';
                if cfg.lane_skew >= 128
                    and (tick mod C_FRAME_PERIOD_CYCLES) > 0
                    and (tick mod C_FRAME_PERIOD_CYCLES) < (3 * cfg.lane_skew)
                then
                    join_pending_v := '1';
                end if;
                join_pending <= join_pending_v;
                inactive_wait <= join_pending_v;
                opq_body_hold <= join_pending_v;
                if join_pending_v = '1' then
                    opq_wait_cycles <= to_unsigned((3 * cfg.lane_skew) - (tick mod C_FRAME_PERIOD_CYCLES), opq_wait_cycles'length);
                else
                    opq_wait_cycles <= (others => '0');
                end if;

                if tick = 0 then
                    flow_state <= to_unsigned(1, flow_state'length);
                elsif tick > (G_CASE_CYCLES - 32) then
                    flow_state <= to_unsigned(5, flow_state'length);
                elsif join_pending_v = '1' then
                    flow_state <= to_unsigned(3, flow_state'length);
                elsif dma_half_full_v = '1' then
                    flow_state <= to_unsigned(4, flow_state'length);
                else
                    flow_state <= to_unsigned(2, flow_state'length);
                end if;

                valid_v := ev_valid(raw3_v) & ev_valid(raw2_v) & ev_valid(raw1_v) & ev_valid(raw0_v);
                fire_v := valid_v and active_mask_v;
                lane_valid <= valid_v;
                lane_ready <= (others => '1');
                lane_fire <= fire_v;
                opq_ingress_accept <= fire_v;

                for lane in 0 to 3 loop
                    if lane_drain_v(lane) > 0 then
                        if lane_state_v(lane) > lane_drain_v(lane) then
                            lane_state_v(lane) := lane_state_v(lane) - lane_drain_v(lane);
                        else
                            lane_state_v(lane) := 0;
                        end if;
                        lane_drain_v(lane) := 0;
                    end if;

                    if ticket_drain_v(lane) > 0 then
                        if ticket_state_v(lane) > ticket_drain_v(lane) then
                            ticket_state_v(lane) := ticket_state_v(lane) - ticket_drain_v(lane);
                        else
                            ticket_state_v(lane) := 0;
                        end if;
                        ticket_drain_v(lane) := 0;
                    end if;
                end loop;

                if handle_drain_v > 0 then
                    if handle_usedw_v > handle_drain_v then
                        handle_usedw_v := handle_usedw_v - handle_drain_v;
                    else
                        handle_usedw_v := 0;
                    end if;
                    handle_drain_v := 0;
                end if;

                drive_event(lane0_data, lane0_datak, lane0_word_kind, lane0_header_id, lane0_source_lane, lane0_frame_ts, lane0_hit_low, lane_ts0_v, raw0_v);
                drive_event(lane1_data, lane1_datak, lane1_word_kind, lane1_header_id, lane1_source_lane, lane1_frame_ts, lane1_hit_low, lane_ts1_v, raw1_v);
                drive_event(lane2_data, lane2_datak, lane2_word_kind, lane2_header_id, lane2_source_lane, lane2_frame_ts, lane2_hit_low, lane_ts2_v, raw2_v);
                drive_event(lane3_data, lane3_datak, lane3_word_kind, lane3_header_id, lane3_source_lane, lane3_frame_ts, lane3_hit_low, lane_ts3_v, raw3_v);
                drive_event(opq_data, opq_datak, opq_word_kind, opq_header_id, opq_source_lane, opq_frame_ts, opq_hit_low, opq_ts_v, raw_opq_v);

                selected_lane_v := 0;
                page_write_v := '0';
                ticket_push_v := (others => '0');
                alloc_grant_lane_v := (others => '0');
                drr_req_raw_v := (others => '0');
                drr_req_eligible_v := (others => '0');
                drr_grant_v := (others => '0');
                drr_defer_v := (others => '0');
                for lane in 0 to 3 loop
                    if valid_v(lane) = '1' then
                        count_kind(lane_kind_v(lane), stat_offered_frame_v, stat_offered_subframe_v, stat_offered_hit_v);
                    end if;
                    if active_mask_v(lane) = '0' then
                        lane_packet_done_v(lane) := '1';
                        lane_packet_open_v(lane) := '0';
                    elsif fire_v(lane) = '1' then
                        if is_header_kind(lane_kind_v(lane)) then
                            lane_packet_done_v(lane) := '0';
                            lane_packet_open_v(lane) := '1';
                        elsif lane_kind_v(lane) = C_KIND_EOP_TRAILER then
                            lane_packet_done_v(lane) := '1';
                            lane_packet_open_v(lane) := '0';
                        end if;
                    end if;

                    if fire_v(lane) = '1' then
                        ingress_count_v := ingress_count_v + 1;
                        lane_accept_v(lane) := lane_accept_v(lane) + 1;
                        lane_wr_ptr_v(lane) := (lane_wr_ptr_v(lane) + 1) mod C_LANE_FIFO_DEPTH;
                        lane_state_v(lane) := fifo_usedw(lane_wr_ptr_v(lane), lane_rd_ptr_v(lane), C_LANE_FIFO_DEPTH);
                        if not is_error_kind(lane_kind_v(lane)) then
                            count_kind(lane_kind_v(lane), stat_ingress_frame_v, stat_ingress_subframe_v, stat_ingress_hit_v);
                        end if;
                        if lane_credit_v(lane) > 0 then
                            lane_credit_v(lane) := lane_credit_v(lane) - 1;
                        end if;
                        case lane is
                            when 0 =>
                                lane_head_word_v(lane) := lane0_word;
                                lane_head_kind_v(lane) := lane_kind_v(lane);
                            when 1 =>
                                lane_head_word_v(lane) := lane1_word;
                                lane_head_kind_v(lane) := lane_kind_v(lane);
                            when 2 =>
                                lane_head_word_v(lane) := lane2_word;
                                lane_head_kind_v(lane) := lane_kind_v(lane);
                            when others =>
                                lane_head_word_v(lane) := lane3_word;
                                lane_head_kind_v(lane) := lane_kind_v(lane);
                        end case;
                    end if;
                end loop;

                page_commit_open_v := false;
                for lane in 0 to 3 loop
                    if active_mask_v(lane) = '1' and lane_packet_done_v(lane) = '0' then
                        page_commit_open_v := true;
                    end if;
                end loop;

                if fire_v(0) = '1' then
                    if is_ticket_kind(lane_kind_v(0)) then ticket_push_v(0) := '1'; end if;
                    if is_header_kind(lane_kind_v(0)) then ft_wr_header_v := ft_wr_header_v + 1; lane_wr_hdr_v(0) := lane_wr_hdr_v(0) + 1; end if;
                    if is_subheader_kind(lane_kind_v(0)) then ft_wr_subh_v := ft_wr_subh_v + 1; lane_wr_shd_v(0) := lane_wr_shd_v(0) + 1; end if;
                    if is_hit_kind(lane_kind_v(0)) then ft_wr_hit_v := ft_wr_hit_v + 1; lane_wr_hit_v(0) := lane_wr_hit_v(0) + 1; end if;
                end if;
                if fire_v(1) = '1' then
                    if is_ticket_kind(lane_kind_v(1)) then ticket_push_v(1) := '1'; end if;
                    if is_header_kind(lane_kind_v(1)) then ft_wr_header_v := ft_wr_header_v + 1; lane_wr_hdr_v(1) := lane_wr_hdr_v(1) + 1; end if;
                    if is_subheader_kind(lane_kind_v(1)) then ft_wr_subh_v := ft_wr_subh_v + 1; lane_wr_shd_v(1) := lane_wr_shd_v(1) + 1; end if;
                    if is_hit_kind(lane_kind_v(1)) then ft_wr_hit_v := ft_wr_hit_v + 1; lane_wr_hit_v(1) := lane_wr_hit_v(1) + 1; end if;
                end if;
                if fire_v(2) = '1' then
                    if is_ticket_kind(lane_kind_v(2)) then ticket_push_v(2) := '1'; end if;
                    if is_header_kind(lane_kind_v(2)) then ft_wr_header_v := ft_wr_header_v + 1; lane_wr_hdr_v(2) := lane_wr_hdr_v(2) + 1; end if;
                    if is_subheader_kind(lane_kind_v(2)) then ft_wr_subh_v := ft_wr_subh_v + 1; lane_wr_shd_v(2) := lane_wr_shd_v(2) + 1; end if;
                    if is_hit_kind(lane_kind_v(2)) then ft_wr_hit_v := ft_wr_hit_v + 1; lane_wr_hit_v(2) := lane_wr_hit_v(2) + 1; end if;
                end if;
                if fire_v(3) = '1' then
                    if is_ticket_kind(lane_kind_v(3)) then ticket_push_v(3) := '1'; end if;
                    if is_header_kind(lane_kind_v(3)) then ft_wr_header_v := ft_wr_header_v + 1; lane_wr_hdr_v(3) := lane_wr_hdr_v(3) + 1; end if;
                    if is_subheader_kind(lane_kind_v(3)) then ft_wr_subh_v := ft_wr_subh_v + 1; lane_wr_shd_v(3) := lane_wr_shd_v(3) + 1; end if;
                    if is_hit_kind(lane_kind_v(3)) then ft_wr_hit_v := ft_wr_hit_v + 1; lane_wr_hit_v(3) := lane_wr_hit_v(3) + 1; end if;
                end if;
                account_drop(raw0_v, 0, valid_v(0) = '1' and active_mask_v(0) = '0',
                    lane_drop_v, lane_drop_hdr_v, lane_drop_shd_v, lane_drop_hit_v,
                    ft_drop_header_v, ft_drop_subh_v, ft_drop_hit_v,
                    stat_drop_controlled_frame_v, stat_drop_controlled_subframe_v, stat_drop_controlled_hit_v,
                    stat_drop_asserted_frame_v, stat_drop_asserted_subframe_v, stat_drop_asserted_hit_v);
                account_drop(raw1_v, 1, valid_v(1) = '1' and active_mask_v(1) = '0',
                    lane_drop_v, lane_drop_hdr_v, lane_drop_shd_v, lane_drop_hit_v,
                    ft_drop_header_v, ft_drop_subh_v, ft_drop_hit_v,
                    stat_drop_controlled_frame_v, stat_drop_controlled_subframe_v, stat_drop_controlled_hit_v,
                    stat_drop_asserted_frame_v, stat_drop_asserted_subframe_v, stat_drop_asserted_hit_v);
                account_drop(raw2_v, 2, valid_v(2) = '1' and active_mask_v(2) = '0',
                    lane_drop_v, lane_drop_hdr_v, lane_drop_shd_v, lane_drop_hit_v,
                    ft_drop_header_v, ft_drop_subh_v, ft_drop_hit_v,
                    stat_drop_controlled_frame_v, stat_drop_controlled_subframe_v, stat_drop_controlled_hit_v,
                    stat_drop_asserted_frame_v, stat_drop_asserted_subframe_v, stat_drop_asserted_hit_v);
                account_drop(raw3_v, 3, valid_v(3) = '1' and active_mask_v(3) = '0',
                    lane_drop_v, lane_drop_hdr_v, lane_drop_shd_v, lane_drop_hit_v,
                    ft_drop_header_v, ft_drop_subh_v, ft_drop_hit_v,
                    stat_drop_controlled_frame_v, stat_drop_controlled_subframe_v, stat_drop_controlled_hit_v,
                    stat_drop_asserted_frame_v, stat_drop_asserted_subframe_v, stat_drop_asserted_hit_v);
                for lane in 0 to 3 loop
                    if ticket_push_v(lane) = '1' and ticket_state_v(lane) < 2047 then
                        ticket_wr_ptr_v(lane) := (ticket_wr_ptr_v(lane) + 1) mod C_TICKET_FIFO_DEPTH;
                        ticket_state_v(lane) := fifo_usedw(ticket_wr_ptr_v(lane), ticket_rd_ptr_v(lane), C_TICKET_FIFO_DEPTH);
                        if ticket_credit_v(lane) > 0 then
                            ticket_credit_v(lane) := ticket_credit_v(lane) - 1;
                        end if;
                    end if;
                end loop;
                opq_ticket_push <= ticket_push_v;

                alloc_req_v := (others => '0');
                for lane in 0 to 3 loop
                    ticket_state_v(lane) := fifo_usedw(ticket_wr_ptr_v(lane), ticket_rd_ptr_v(lane), C_TICKET_FIFO_DEPTH);
                    if ticket_state_v(lane) > 0 then
                        alloc_req_v(lane) := '1';
                    end if;
                end loop;
                alloc_lane_v := allocator_rr_v;
                for offset in 0 to 3 loop
                    candidate_lane_v := (allocator_rr_v + offset) mod 4;
                    if alloc_req_v(candidate_lane_v) = '1' and alloc_grant_lane_v = "0000" then
                        alloc_lane_v := candidate_lane_v;
                        alloc_grant_lane_v(candidate_lane_v) := '1';
                    end if;
                end loop;
                if alloc_grant_lane_v /= "0000" then
                    selected_lane_v := alloc_lane_v;
                    if ticket_state_v(selected_lane_v) > 0 then
                        ticket_rd_ptr_v(selected_lane_v) := (ticket_rd_ptr_v(selected_lane_v) + 1) mod C_TICKET_FIFO_DEPTH;
                        ticket_state_v(selected_lane_v) := fifo_usedw(ticket_wr_ptr_v(selected_lane_v), ticket_rd_ptr_v(selected_lane_v), C_TICKET_FIFO_DEPTH);
                    end if;
                    if ticket_credit_v(selected_lane_v) < C_TICKET_FIFO_MAX_CREDIT then
                        ticket_credit_v(selected_lane_v) := ticket_credit_v(selected_lane_v) + 1;
                    end if;
                    if handle_usedw_v < 2047 then
                        handle_usedw_v := handle_usedw_v + 1;
                    end if;
                    ticket_id_v := ticket_id_v + 1;
                    allocator_rr_v := (selected_lane_v + 1) mod 4;
                end if;
                opq_allocator_req <= alloc_req_v;
                opq_allocator_grant <= '1' when alloc_grant_lane_v /= "0000" else '0';
                opq_allocator_grant_lane <= alloc_grant_lane_v;
                opq_allocator_ticket_valid <= '1' when alloc_grant_lane_v /= "0000" else '0';
                opq_allocator_ticket_lane <= to_unsigned(selected_lane_v, opq_allocator_ticket_lane'length);
                opq_allocator_ticket_id <= to_unsigned(ticket_id_v, opq_allocator_ticket_id'length);

                for lane in 0 to 3 loop
                    lane_state_v(lane) := fifo_usedw(lane_wr_ptr_v(lane), lane_rd_ptr_v(lane), C_LANE_FIFO_DEPTH);
                    if lane_state_v(lane) > 0 then
                        drr_req_raw_v(lane) := '1';
                        if drr_quantum_v(lane) > 0 and dma_half_full_v = '0' then
                            drr_req_eligible_v(lane) := '1';
                        end if;
                    end if;
                end loop;
                drr_selected_lane_v := drr_rr_v;
                for offset in 0 to 3 loop
                    candidate_lane_v := (drr_rr_v + offset) mod 4;
                    if drr_req_eligible_v(candidate_lane_v) = '1' and drr_grant_v = "0000" then
                        drr_selected_lane_v := candidate_lane_v;
                        drr_grant_v(candidate_lane_v) := '1';
                    end if;
                end loop;
                if drr_grant_v /= "0000" then
                    drr_lane_v := drr_selected_lane_v;
                    if ev_valid(raw_opq_v) = '0' then
                        page_write_v := '1';
                    else
                        page_write_v := '0';
                    end if;
                    if lane_state_v(drr_lane_v) > 0 then
                        lane_rd_ptr_v(drr_lane_v) := (lane_rd_ptr_v(drr_lane_v) + 1) mod C_LANE_FIFO_DEPTH;
                        lane_state_v(drr_lane_v) := fifo_usedw(lane_wr_ptr_v(drr_lane_v), lane_rd_ptr_v(drr_lane_v), C_LANE_FIFO_DEPTH);
                    end if;
                    if lane_credit_v(drr_lane_v) < C_LANE_FIFO_MAX_CREDIT then
                        lane_credit_v(drr_lane_v) := lane_credit_v(drr_lane_v) + 1;
                    end if;
                    if drr_quantum_v(drr_lane_v) > 0 then
                        drr_quantum_v(drr_lane_v) := drr_quantum_v(drr_lane_v) - 1;
                    end if;
                    drr_grant_cnt_v(drr_lane_v) := drr_grant_cnt_v(drr_lane_v) + 1;
                    drr_beat_cnt_v(drr_lane_v) := drr_beat_cnt_v(drr_lane_v) + 1;
                    if handle_usedw_v > 0 then
                        handle_usedw_v := handle_usedw_v - 1;
                    end if;
                    if page_write_v = '1' and page_usedw_v < 4096 then
                        page_usedw_v := page_usedw_v + 1;
                    end if;
                    if is_header_kind(lane_head_kind_v(drr_lane_v)) then lane_rd_hdr_v(drr_lane_v) := lane_rd_hdr_v(drr_lane_v) + 1; end if;
                    if is_subheader_kind(lane_head_kind_v(drr_lane_v)) then lane_rd_shd_v(drr_lane_v) := lane_rd_shd_v(drr_lane_v) + 1; end if;
                    if is_hit_kind(lane_head_kind_v(drr_lane_v)) then lane_rd_hit_v(drr_lane_v) := lane_rd_hit_v(drr_lane_v) + 1; end if;
                    drr_rr_v := (drr_lane_v + 1) mod 4;
                elsif drr_req_raw_v /= "0000" and dma_half_full_v = '0' then
                    for lane in 0 to 3 loop
                        if drr_req_raw_v(lane) = '1' then
                            drr_defer_v(lane) := '1';
                            drr_defer_cnt_v(lane) := drr_defer_cnt_v(lane) + 1;
                            if drr_quantum_v(lane) + C_DRR_DEFAULT_ALLOWANCE > C_DRR_QUANTUM_MAX then
                                drr_quantum_v(lane) := C_DRR_QUANTUM_MAX;
                            else
                                drr_quantum_v(lane) := drr_quantum_v(lane) + C_DRR_DEFAULT_ALLOWANCE;
                            end if;
                        end if;
                    end loop;
                end if;

                opq_drr_req_raw <= drr_req_raw_v;
                opq_drr_req_eligible <= drr_req_eligible_v;
                opq_drr_grant <= drr_grant_v;
                opq_drr_lock_event <= drr_grant_v;
                opq_drr_defer_event <= drr_defer_v;
                opq_drr_selected_lane <= to_unsigned(drr_lane_v, opq_drr_selected_lane'length);
                opq_mover_cmd_valid <= page_write_v;
                opq_mover_cmd_ready <= not dma_half_full_v;
                opq_mover_cmd_lane <= to_unsigned(drr_lane_v, opq_mover_cmd_lane'length);
                opq_mover_cmd_page <= to_unsigned(page_usedw_v, opq_mover_cmd_page'length);
                opq_mover_data_valid <= page_write_v;
                opq_page_ram_we <= page_write_v;
                opq_page_ram_waddr <= to_unsigned(page_usedw_v, opq_page_ram_waddr'length);
                opq_page_ram_wdata <= lane_head_word_v(drr_lane_v);

                opq_kind_v := ev_kind(raw_opq_v);
                if ev_valid(raw_opq_v) = '1' then
                    opq_count_v := opq_count_v + 1;
                    opq_lane_v := ev_source_lane(raw_opq_v);
                    opq_lane_provenance <= to_unsigned(4, opq_lane_provenance'length);
                    if page_usedw_v > 0 then
                        page_usedw_v := page_usedw_v - 1;
                    end if;
                    if is_header_kind(opq_kind_v) then ft_rd_header_v := ft_rd_header_v + 1; end if;
                    if is_subheader_kind(opq_kind_v) then ft_rd_subh_v := ft_rd_subh_v + 1; end if;
                    if is_hit_kind(opq_kind_v) then ft_rd_hit_v := ft_rd_hit_v + 1; end if;
                    if not is_error_kind(opq_kind_v) then
                        count_kind(opq_kind_v, stat_egress_frame_v, stat_egress_subframe_v, stat_egress_hit_v);
                    end if;
                else
                    opq_lane_provenance <= to_unsigned(5, opq_lane_provenance'length);
                end if;
                opq_presenter_valid <= ev_valid(raw_opq_v);
                opq_presenter_ready <= not dma_half_full_v;

                if dma_half_full_v = '0' and ev_valid(raw_opq_v) = '1' and is_hit_kind(opq_kind_v) then
                    dma_wren <= '1';
                    payload_count_v := payload_count_v + 1;
                    dma_count_v := dma_count_v + 1;
                    drive_event(dma_data, dma_datak, dma_word_kind, dma_header_id, dma_source_lane, dma_frame_ts, dma_hit_low, dma_ts_v, raw_opq_v);
                    dma_word_kind <= to_unsigned(C_KIND_DMA_HIT_PAYLOAD, dma_word_kind'length);
                else
                    dma_wren <= '0';
                    dma_data <= (others => '0');
                    dma_datak <= (others => '0');
                    dma_word_kind <= to_unsigned(C_KIND_IDLE, dma_word_kind'length);
                    dma_header_id <= (others => '0');
                    dma_source_lane <= (others => '0');
                    dma_hit_low <= (others => '0');
                end if;

                sync_fifo_signals;
                sync_counter_signals;
                sync_stat_signals;
                reorder_depth <= to_unsigned(handle_usedw_v + page_usedw_v, reorder_depth'length);
                ingress_words <= to_unsigned(ingress_count_v, ingress_words'length);
                opq_words <= to_unsigned(opq_count_v, opq_words'length);
                expected_words <= to_unsigned(opq_count_v, expected_words'length);
                payload_words <= to_unsigned(payload_count_v, payload_words'length);
                dma_words <= to_unsigned(dma_count_v, dma_words'length);
                csr_status_v := (others => '0');
                csr_status_v(3 downto 0) := unsigned(active_mask_v);
                if alloc_req_v /= "0000" then
                    csr_status_v(16) := '1';
                end if;
                if drr_req_raw_v /= "0000" or drr_grant_v /= "0000" then
                    csr_status_v(17) := '1';
                end if;
                csr_status_v(18) := ev_valid(raw_opq_v);
                if active_mask_v /= "1111" then
                    csr_status_v(19) := '1';
                end if;
                csr_status_v(23 downto 20) := to_unsigned(4, 4);
                csr_status <= csr_status_v;
                ghost_count <= (others => '0');
                missing_count <= to_unsigned(stat_drop_inferred_hit_v, missing_count'length);
                dma_done <= '0';
            end loop;

            file_close(lane0_file);
            file_close(lane1_file);
            file_close(lane2_file);
            file_close(lane3_file);
            file_close(opq_file);

            wait until rising_edge(clk);
            cycle_tick <= cycle_tick + 1;
            case_eop <= '0';
            case_sop <= '0';
            segment_reset <= '0';
            bucket_transition <= '0';
            lane_valid <= (others => '0');
            lane_fire <= (others => '0');
            opq_ingress_accept <= (others => '0');
            opq_ticket_push <= (others => '0');
            opq_allocator_req <= (others => '0');
            opq_allocator_grant <= '0';
            opq_allocator_grant_lane <= (others => '0');
            opq_allocator_ticket_valid <= '0';
            opq_mover_cmd_valid <= '0';
            opq_mover_data_valid <= '0';
            opq_drr_req_raw <= (others => '0');
            opq_drr_req_eligible <= (others => '0');
            opq_drr_grant <= (others => '0');
            opq_drr_lock_event <= (others => '0');
            opq_drr_defer_event <= (others => '0');
            opq_page_ram_we <= '0';
            opq_presenter_valid <= '0';
            dma_wren <= '0';
            dma_half_full <= '0';
            dma_done <= '1';
            scoreboard_pass <= '1';
            cases_done <= to_unsigned(idx + 1, cases_done'length);

            report "[GHDL_CASE_PASS] case=" & case_name(cfg.code)
                & " ingress_words=" & integer'image(ingress_count_v)
                & " opq_words=" & integer'image(opq_count_v)
                & " dma_hit_words=" & integer'image(dma_count_v)
                severity note;
        end loop;

        wait until rising_edge(clk);
        cycle_tick <= cycle_tick + 1;
        dma_done <= '0';
        run_active <= '0';
        flow_state <= to_unsigned(6, flow_state'length);
        report "[GHDL_CROSS_PASS] cases=" & integer'image(C_CASES'length)
            & " ghost=0 missing=0"
            severity note;
        wait until rising_edge(clk);
        cycle_tick <= cycle_tick + 1;
        stop;
        wait;
    end process;

end architecture;
